/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-04-14 09:11:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.amritcare.dao.*;
import com.amritcare.model.*;
import java.util.List;

public final class admin_005fdashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.amritcare.model");
    _jspx_imports_packages.add("com.amritcare.dao");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    if (session.getAttribute("loggedUser")==null) { response.sendRedirect("login.jsp"); return; }
    User user = (User) session.getAttribute("loggedUser");
    if (!"city_admin".equals(user.getRole())) { response.sendRedirect("login.jsp"); return; }

    HospitalDAO hDao = new HospitalDAO();
    BookingDAO  bDao = new BookingDAO();
    UserDAO     uDao = new UserDAO();

    List<Hospital> hospitals = hDao.getAllHospitals();
    List<Booking>  bookings  = bDao.getAllBookings();

    int totalHospitals = hDao.getTotalHospitals();
    int totalBookings  = bDao.getTotalBookings();
    int totalPatients  = uDao.getTotalPatients();

    int totalAvailBeds  = hospitals.stream().mapToInt(Hospital::getAvailableBeds).sum();
    int totalAvailIcu   = hospitals.stream().mapToInt(Hospital::getAvailableIcu).sum();
    int totalAvailDocs  = hospitals.stream().mapToInt(Hospital::getAvailableDoctors).sum();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>City Admin Dashboard — AmritCare</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<nav class=\"navbar\">\n");
      out.write("  <a href=\"index.jsp\" class=\"navbar-brand\"><span class=\"logo-icon\">🏥</span> AmritCare</a>\n");
      out.write("  <ul class=\"nav-links\">\n");
      out.write("    <li><a href=\"admin_dashboard.jsp\" class=\"active\">Dashboard</a></li>\n");
      out.write("    <li><a href=\"manage_hospitals.jsp\">Hospitals</a></li>\n");
      out.write("    <li><a href=\"reports.jsp\">Reports</a></li>\n");
      out.write("    <li><a href=\"LogoutServlet\">Logout</a></li>\n");
      out.write("  </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"dashboard-layout\">\n");
      out.write("\n");
      out.write("  <aside class=\"sidebar\">\n");
      out.write("    <div class=\"sidebar-user\">\n");
      out.write("      <div class=\"avatar\">A</div>\n");
      out.write("      <div class=\"user-name\">City Administrator</div>\n");
      out.write("      <div class=\"user-role\">Super Admin</div>\n");
      out.write("    </div>\n");
      out.write("    <ul class=\"sidebar-nav\">\n");
      out.write("      <li><a href=\"admin_dashboard.jsp\" class=\"active\"><span class=\"nav-icon\">📊</span> Dashboard</a></li>\n");
      out.write("      <li><a href=\"manage_hospitals.jsp\"><span class=\"nav-icon\">🏥</span> Manage Hospitals</a></li>\n");
      out.write("      <li><a href=\"reports.jsp\"><span class=\"nav-icon\">📈</span> Reports</a></li>\n");
      out.write("      <li><a href=\"ambulance.jsp\"><span class=\"nav-icon\">🚑</span> Ambulance</a></li>\n");
      out.write("      <li><a href=\"LogoutServlet\"><span class=\"nav-icon\">🚪</span> Logout</a></li>\n");
      out.write("    </ul>\n");
      out.write("  </aside>\n");
      out.write("\n");
      out.write("  <main class=\"dashboard-content\">\n");
      out.write("\n");
      out.write("    <div style=\"display:flex;align-items:center;justify-content:space-between;margin-bottom:1.5rem;flex-wrap:wrap;gap:1rem\">\n");
      out.write("      <div>\n");
      out.write("        <h1 style=\"font-family:'Playfair Display',serif;font-size:1.8rem\">🌆 City Health Overview</h1>\n");
      out.write("        <p style=\"color:var(--muted)\">Real-time resource status across Bhopal</p>\n");
      out.write("      </div>\n");
      out.write("      <a href=\"manage_hospitals.jsp\" class=\"btn btn-primary\">+ Add Hospital</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- KPI Row -->\n");
      out.write("    <div class=\"grid-4\" style=\"margin-bottom:2rem\">\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon blue\">🏥</div>\n");
      out.write("        <div><div class=\"stat-value\">");
      out.print( totalHospitals );
      out.write("</div><div class=\"stat-label\">Active Hospitals</div></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon green\">👥</div>\n");
      out.write("        <div><div class=\"stat-value\">");
      out.print( totalPatients );
      out.write("</div><div class=\"stat-label\">Registered Patients</div></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon orange\">📅</div>\n");
      out.write("        <div><div class=\"stat-value\">");
      out.print( totalBookings );
      out.write("</div><div class=\"stat-label\">Total Bookings</div></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon red\">🚑</div>\n");
      out.write("        <div><div class=\"stat-value\">5</div><div class=\"stat-label\">Ambulances</div></div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Resource Summary -->\n");
      out.write("    <div class=\"grid-3\" style=\"margin-bottom:2rem\">\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon green\">🛏</div>\n");
      out.write("        <div><div class=\"stat-value\">");
      out.print( totalAvailBeds );
      out.write("</div><div class=\"stat-label\">Available Beds (City)</div></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon blue\">🏥</div>\n");
      out.write("        <div><div class=\"stat-value\">");
      out.print( totalAvailIcu );
      out.write("</div><div class=\"stat-label\">Available ICU (City)</div></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon green\">👨‍⚕️</div>\n");
      out.write("        <div><div class=\"stat-value\">");
      out.print( totalAvailDocs );
      out.write("</div><div class=\"stat-label\">Available Doctors</div></div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Hospital Overview Table -->\n");
      out.write("    <div class=\"table-wrapper mb-3\" style=\"margin-bottom:1.5rem\">\n");
      out.write("      <div class=\"card-header\">\n");
      out.write("        <strong>🏥 Hospital Status</strong>\n");
      out.write("        <a href=\"manage_hospitals.jsp\" class=\"btn btn-primary btn-sm\">Manage</a>\n");
      out.write("      </div>\n");
      out.write("      <table>\n");
      out.write("        <thead>\n");
      out.write("          <tr><th>Hospital</th><th>Location</th><th>Beds Available</th><th>ICU Available</th><th>Doctors</th><th>Rating</th><th>Status</th></tr>\n");
      out.write("        </thead>\n");
      out.write("        <tbody>\n");
      out.write("          ");
 for (Hospital h : hospitals) { 
      out.write("\n");
      out.write("          <tr>\n");
      out.write("            <td><strong>");
      out.print( h.getName() );
      out.write("</strong></td>\n");
      out.write("            <td style=\"font-size:0.85rem\">");
      out.print( h.getLocation() );
      out.write("</td>\n");
      out.write("            <td>\n");
      out.write("              <span style=\"color:");
      out.print( h.getAvailableBeds()>5?"var(--success)":h.getAvailableBeds()>0?"var(--warning)":"var(--danger)" );
      out.write(";font-weight:700\">\n");
      out.write("                ");
      out.print( h.getAvailableBeds() );
      out.write("\n");
      out.write("              </span>\n");
      out.write("            </td>\n");
      out.write("            <td>\n");
      out.write("              <span style=\"color:");
      out.print( h.getAvailableIcu()>2?"var(--success)":h.getAvailableIcu()>0?"var(--warning)":"var(--danger)" );
      out.write(";font-weight:700\">\n");
      out.write("                ");
      out.print( h.getAvailableIcu() );
      out.write("\n");
      out.write("              </span>\n");
      out.write("            </td>\n");
      out.write("            <td>");
      out.print( h.getAvailableDoctors() );
      out.write("</td>\n");
      out.write("            <td>⭐ ");
      out.print( h.getRating() );
      out.write("</td>\n");
      out.write("            <td><span class=\"badge badge-success\">ACTIVE</span></td>\n");
      out.write("          </tr>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Recent Bookings -->\n");
      out.write("    <div class=\"table-wrapper\">\n");
      out.write("      <div class=\"card-header\">\n");
      out.write("        <strong>📋 Recent Bookings</strong>\n");
      out.write("        <a href=\"reports.jsp\" class=\"btn btn-outline btn-sm\">View All</a>\n");
      out.write("      </div>\n");
      out.write("      <table>\n");
      out.write("        <thead>\n");
      out.write("          <tr><th>#</th><th>Patient</th><th>Hospital</th><th>Type</th><th>Date</th><th>Status</th></tr>\n");
      out.write("        </thead>\n");
      out.write("        <tbody>\n");
      out.write("          ");
 List<Booking> recent = bookings.subList(0, Math.min(10, bookings.size())); 
      out.write("\n");
      out.write("          ");
 for (Booking b : recent) {
               String bc = "badge-secondary";
               if ("confirmed".equals(b.getStatus())) bc="badge-success";
               else if ("pending".equals(b.getStatus())) bc="badge-warning";
               else if ("cancelled".equals(b.getStatus())) bc="badge-danger";
          
      out.write("\n");
      out.write("          <tr>\n");
      out.write("            <td>#");
      out.print( b.getBookingId() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( b.getPatientName() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( b.getHospitalName() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( b.getBookingType() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( b.getBookingDate() );
      out.write("</td>\n");
      out.write("            <td><span class=\"badge ");
      out.print( bc );
      out.write('"');
      out.write('>');
      out.print( b.getStatus().toUpperCase() );
      out.write("</span></td>\n");
      out.write("          </tr>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("          ");
 if (bookings.isEmpty()) { 
      out.write("\n");
      out.write("          <tr><td colspan=\"6\" style=\"text-align:center;color:var(--muted);padding:2rem\">No bookings yet</td></tr>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  </main>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<button class=\"voice-btn\" id=\"voiceBtn\">🎤</button>\n");
      out.write("<div class=\"voice-tooltip\" id=\"voiceTooltip\"></div>\n");
      out.write("<script src=\"js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
