/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-04-14 09:43:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.amritcare.dao.*;
import com.amritcare.model.*;
import java.util.List;

public final class ambulance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.amritcare.model");
    _jspx_imports_packages.add("com.amritcare.dao");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    AmbulanceDAO aDao = new AmbulanceDAO();
    HospitalDAO  hDao = new HospitalDAO();
    List<Ambulance> ambulances = aDao.getAllAmbulances();
    List<Hospital>  hospitals  = hDao.getAllHospitals();
    String userName = (String) session.getAttribute("userName");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Ambulance Tracking — AmritCare</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("  <style>\n");
      out.write("    #mapContainer { height: 500px; border-radius: var(--radius); overflow:hidden; background:#e8f4f8; position:relative; }\n");
      out.write("    .map-placeholder {\n");
      out.write("      width:100%; height:100%;\n");
      out.write("      background: linear-gradient(135deg, #d0e8f2 0%, #b8daf0 100%);\n");
      out.write("      display:flex; flex-direction:column; align-items:center; justify-content:center;\n");
      out.write("      color: var(--primary-dark);\n");
      out.write("    }\n");
      out.write("    .sim-canvas { position:absolute; top:0; left:0; width:100%; height:100%; }\n");
      out.write("    .status-available { color: var(--success); }\n");
      out.write("    .status-on_call   { color: var(--danger); }\n");
      out.write("    .status-returning { color: var(--warning); }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<nav class=\"navbar\">\n");
      out.write("  <a href=\"index.jsp\" class=\"navbar-brand\"><span class=\"logo-icon\">🏥</span> AmritCare</a>\n");
      out.write("  <ul class=\"nav-links\">\n");
      out.write("    <li><a href=\"index.jsp\">Home</a></li>\n");
      out.write("    <li><a href=\"HospitalServlet\">Hospitals</a></li>\n");
      out.write("    <li><a href=\"ambulance.jsp\" class=\"active\">🚑 Ambulance</a></li>\n");
      out.write("    ");
 if (userName != null) { 
      out.write("\n");
      out.write("      <li><a href=\"dashboard.jsp\">Dashboard</a></li>\n");
      out.write("      <li><a href=\"LogoutServlet\">Logout</a></li>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("      <li><a href=\"login.jsp\">Login</a></li>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div style=\"background:linear-gradient(135deg,#b71c1c,#ef233c);color:#fff;padding:2.5rem 2rem 2rem;\">\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <h1 style=\"font-family:'Playfair Display',serif;font-size:2rem\">🚑 Live Ambulance Tracking</h1>\n");
      out.write("    <p style=\"opacity:0.85\">Real-time location of city ambulances — Bhopal</p>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<section class=\"section\">\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <div class=\"grid-2\" style=\"gap:2rem;align-items:start\">\n");
      out.write("\n");
      out.write("      <!-- Map / Simulation -->\n");
      out.write("      <div>\n");
      out.write("        <div class=\"card\">\n");
      out.write("          <div class=\"card-header\">\n");
      out.write("            <strong>🗺️ Live Map</strong>\n");
      out.write("            <div style=\"display:flex;gap:8px;align-items:center;font-size:0.82rem\">\n");
      out.write("              <span style=\"color:var(--success)\">🟢 Available</span>\n");
      out.write("              <span style=\"color:var(--danger)\">🔴 On Call</span>\n");
      out.write("              <span style=\"color:var(--warning)\">🟡 Returning</span>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div id=\"mapContainer\">\n");
      out.write("            <canvas class=\"sim-canvas\" id=\"ambulanceCanvas\"></canvas>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <p style=\"font-size:0.8rem;color:var(--muted);margin-top:0.5rem;text-align:center\">\n");
      out.write("          📍 Simulated map of Bhopal, Madhya Pradesh. Markers update every 3 seconds.\n");
      out.write("          <br>For production, integrate Google Maps API key.\n");
      out.write("        </p>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- Ambulance List -->\n");
      out.write("      <div>\n");
      out.write("        <div class=\"card\">\n");
      out.write("          <div class=\"card-header\"><strong>🚑 Fleet Status (");
      out.print( ambulances.size() );
      out.write(" units)</strong></div>\n");
      out.write("          <div class=\"ambulance-list\">\n");
      out.write("            ");
 for (Ambulance a : ambulances) { 
      out.write("\n");
      out.write("            <div class=\"ambulance-item\" onclick=\"focusAmbulance(");
      out.print( a.getId() );
      out.write(")\">\n");
      out.write("              <div class=\"amb-icon\">🚑</div>\n");
      out.write("              <div style=\"flex:1\">\n");
      out.write("                <div style=\"font-weight:600\">");
      out.print( a.getVehicleNumber() );
      out.write("</div>\n");
      out.write("                <div style=\"font-size:0.82rem;color:var(--muted)\">Driver: ");
      out.print( a.getDriverName() );
      out.write(' ');
      out.write('·');
      out.write(' ');
      out.print( a.getContact() );
      out.write("</div>\n");
      out.write("                <div style=\"font-size:0.82rem;color:var(--muted)\">Base: ");
      out.print( a.getHospitalName()!=null?a.getHospitalName():"—" );
      out.write("</div>\n");
      out.write("              </div>\n");
      out.write("              <div>\n");
      out.write("                <span class=\"badge ");
      out.print( "available".equals(a.getStatus())?"badge-success":"on_call".equals(a.getStatus())?"badge-danger":"badge-warning" );
      out.write("\">\n");
      out.write("                  ");
      out.print( a.getStatus().replace("_"," ").toUpperCase() );
      out.write("\n");
      out.write("                </span>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Emergency Call Box -->\n");
      out.write("        <div class=\"card\" style=\"margin-top:1.5rem;border-left:4px solid var(--danger)\">\n");
      out.write("          <div class=\"card-body\" style=\"text-align:center;padding:1.5rem\">\n");
      out.write("            <div style=\"font-size:2.5rem;margin-bottom:0.75rem\">🆘</div>\n");
      out.write("            <h3 style=\"font-family:'Playfair Display',serif;margin-bottom:0.5rem;color:var(--danger)\">Emergency?</h3>\n");
      out.write("            <p style=\"color:var(--muted);font-size:0.9rem;margin-bottom:1rem\">Call our 24/7 ambulance dispatch immediately</p>\n");
      out.write("            <a href=\"tel:108\" class=\"btn btn-danger btn-lg\" style=\"width:100%;justify-content:center\">📞 Call 108 — Ambulance</a>\n");
      out.write("            <p style=\"margin-top:0.75rem;font-size:0.8rem;color:var(--muted)\">Free emergency service · Available 24/7</p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Nearest Hospitals -->\n");
      out.write("        <div class=\"card\" style=\"margin-top:1.5rem\">\n");
      out.write("          <div class=\"card-header\"><strong>🏥 Nearest Hospitals</strong></div>\n");
      out.write("          ");
 int count=0; for (Hospital h : hospitals) { if(count++>=3) break; 
      out.write("\n");
      out.write("          <div style=\"padding:12px 16px;border-bottom:1px solid var(--border);display:flex;align-items:center;gap:12px\">\n");
      out.write("            <span style=\"font-size:1.5rem\">🏥</span>\n");
      out.write("            <div style=\"flex:1\">\n");
      out.write("              <div style=\"font-weight:600;font-size:0.9rem\">");
      out.print( h.getName() );
      out.write("</div>\n");
      out.write("              <div style=\"font-size:0.8rem;color:var(--muted)\">");
      out.print( h.getLocation() );
      out.write("</div>\n");
      out.write("            </div>\n");
      out.write("            <div style=\"text-align:right;font-size:0.82rem\">\n");
      out.write("              <div style=\"color:var(--success);font-weight:600\">🛏 ");
      out.print( h.getAvailableBeds() );
      out.write(" beds</div>\n");
      out.write("              <div style=\"color:var(--primary)\">🏥 ");
      out.print( h.getAvailableIcu() );
      out.write(" ICU</div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer><p>© 2026 AmritCare — Emergency Helpline: 108</p></footer>\n");
      out.write("\n");
      out.write("<button class=\"voice-btn\" id=\"voiceBtn\">🎤</button>\n");
      out.write("<div class=\"voice-tooltip\" id=\"voiceTooltip\"></div>\n");
      out.write("<script src=\"js/main.js\"></script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("const canvas = document.getElementById('ambulanceCanvas');\n");
      out.write("const ctx    = canvas.getContext('2d');\n");
      out.write("\n");
      out.write("\n");
      out.write("function resizeCanvas() {\n");
      out.write("  const container = document.getElementById('mapContainer');\n");
      out.write("  canvas.width  = container.offsetWidth;\n");
      out.write("  canvas.height = container.offsetHeight;\n");
      out.write("}\n");
      out.write("resizeCanvas();\n");
      out.write("window.addEventListener('resize', () => { resizeCanvas(); drawMap(); });\n");
      out.write("\n");
      out.write("\n");
      out.write("const hospitals = [\n");
      out.write("  ");
 for (Hospital h : hospitals) { 
      out.write("\n");
      out.write("  { name: \"");
      out.print( h.getName().replace("\"","") );
      out.write("\", lat: ");
      out.print( h.getLatitude() );
      out.write(", lng: ");
      out.print( h.getLongitude() );
      out.write(" },\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("];\n");
      out.write("\n");
      out.write("const ambulances = [\n");
      out.write("  ");
 for (Ambulance a : ambulances) { 
      out.write("\n");
      out.write("  { id: ");
      out.print( a.getId() );
      out.write(", vehicle: \"");
      out.print( a.getVehicleNumber() );
      out.write("\", lat: ");
      out.print( a.getCurrentLat() );
      out.write(", lng: ");
      out.print( a.getCurrentLng() );
      out.write(", status: \"");
      out.print( a.getStatus() );
      out.write("\",\n");
      out.write("    vLat: (Math.random()-0.5)*0.0003, vLng: (Math.random()-0.5)*0.0003 },\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("];\n");
      out.write("\n");
      out.write("\n");
      out.write("const mapBounds = { minLat:23.18, maxLat:23.32, minLng:77.36, maxLng:77.52 };\n");
      out.write("\n");
      out.write("function latLngToXY(lat, lng) {\n");
      out.write("  const x = ((lng - mapBounds.minLng) / (mapBounds.maxLng - mapBounds.minLng)) * canvas.width;\n");
      out.write("  const y = ((mapBounds.maxLat - lat) / (mapBounds.maxLat - mapBounds.minLat)) * canvas.height;\n");
      out.write("  return { x, y };\n");
      out.write("}\n");
      out.write("\n");
      out.write("function drawMap() {\n");
      out.write("  ctx.clearRect(0, 0, canvas.width, canvas.height);\n");
      out.write("\n");
      out.write("\n");
      out.write("  const grad = ctx.createLinearGradient(0, 0, canvas.width, canvas.height);\n");
      out.write("  grad.addColorStop(0, '#d4e9f7');\n");
      out.write("  grad.addColorStop(1, '#c2ddf0');\n");
      out.write("  ctx.fillStyle = grad;\n");
      out.write("  ctx.fillRect(0, 0, canvas.width, canvas.height);\n");
      out.write("\n");
      out.write("\n");
      out.write("  ctx.strokeStyle = '#b0c8dd'; ctx.lineWidth = 2;\n");
      out.write("  [0.3,0.5,0.7].forEach(r => {\n");
      out.write("    ctx.beginPath(); ctx.moveTo(0, canvas.height*r); ctx.lineTo(canvas.width, canvas.height*r); ctx.stroke();\n");
      out.write("    ctx.beginPath(); ctx.moveTo(canvas.width*r, 0); ctx.lineTo(canvas.width*r, canvas.height); ctx.stroke();\n");
      out.write("  });\n");
      out.write("\n");
      out.write("  \n");
      out.write("  hospitals.forEach((h, i) => {\n");
      out.write("    const pos = latLngToXY(h.lat, h.lng);\n");
      out.write("    ctx.beginPath();\n");
      out.write("    ctx.arc(pos.x, pos.y, 14, 0, Math.PI*2);\n");
      out.write("    ctx.fillStyle = 'rgba(0,119,182,0.85)';\n");
      out.write("    ctx.fill();\n");
      out.write("    ctx.strokeStyle = '#fff'; ctx.lineWidth = 2; ctx.stroke();\n");
      out.write("\n");
      out.write("    \n");
      out.write("    ctx.fillStyle = '#fff';\n");
      out.write("    ctx.font = 'bold 12px sans-serif';\n");
      out.write("    ctx.textAlign = 'center';\n");
      out.write("    ctx.textBaseline = 'middle';\n");
      out.write("    ctx.fillText('H', pos.x, pos.y);\n");
      out.write("\n");
      out.write("    \n");
      out.write("    ctx.fillStyle = '#023e8a';\n");
      out.write("    ctx.font = '10px DM Sans, sans-serif';\n");
      out.write("    ctx.fillText(h.name.split(' ')[0], pos.x, pos.y + 22);\n");
      out.write("  });\n");
      out.write("\n");
      out.write("  \n");
      out.write("  ambulances.forEach(a => {\n");
      out.write("    const pos = latLngToXY(a.lat, a.lng);\n");
      out.write("    const color = a.status==='available' ? '#06d6a0' : a.status==='on_call' ? '#ef233c' : '#ffd166';\n");
      out.write("\n");
      out.write("   \n");
      out.write("    ctx.beginPath();\n");
      out.write("    ctx.arc(pos.x+2, pos.y+2, 12, 0, Math.PI*2);\n");
      out.write("    ctx.fillStyle = 'rgba(0,0,0,0.15)';\n");
      out.write("    ctx.fill();\n");
      out.write("\n");
      out.write("    ctx.beginPath();\n");
      out.write("    ctx.arc(pos.x, pos.y, 12, 0, Math.PI*2);\n");
      out.write("    ctx.fillStyle = color;\n");
      out.write("    ctx.fill();\n");
      out.write("    ctx.strokeStyle = '#fff'; ctx.lineWidth = 2; ctx.stroke();\n");
      out.write("\n");
      out.write("\n");
      out.write("    ctx.fillStyle = '#fff';\n");
      out.write("    ctx.font = '12px sans-serif';\n");
      out.write("    ctx.textAlign = 'center';\n");
      out.write("    ctx.textBaseline = 'middle';\n");
      out.write("    ctx.fillText('🚑', pos.x, pos.y);\n");
      out.write("\n");
      out.write("   \n");
      out.write("    ctx.fillStyle = '#333';\n");
      out.write("    ctx.font = '9px sans-serif';\n");
      out.write("    ctx.fillText(a.vehicle.split('-').pop(), pos.x, pos.y + 20);\n");
      out.write("  });\n");
      out.write("\n");
      out.write("  \n");
      out.write("  ctx.font = 'bold 11px sans-serif';\n");
      out.write("  [['#06d6a0','Available'],['#ef233c','On Call'],['#ffd166','Returning']].forEach(([c,l],i) => {\n");
      out.write("    ctx.beginPath(); ctx.arc(14, 14+i*20, 6, 0, Math.PI*2); ctx.fillStyle=c; ctx.fill();\n");
      out.write("    ctx.fillStyle='#333'; ctx.textAlign='left'; ctx.textBaseline='middle';\n");
      out.write("    ctx.fillText(l, 24, 14+i*20);\n");
      out.write("  });\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("function updateAmbulances() {\n");
      out.write("  ambulances.forEach(a => {\n");
      out.write("    a.lat += a.vLat + (Math.random()-0.5)*0.0001;\n");
      out.write("    a.lng += a.vLng + (Math.random()-0.5)*0.0001;\n");
      out.write("    \n");
      out.write("    if (a.lat < mapBounds.minLat || a.lat > mapBounds.maxLat) a.vLat *= -1;\n");
      out.write("    if (a.lng < mapBounds.minLng || a.lng > mapBounds.maxLng) a.vLng *= -1;\n");
      out.write("    a.lat = Math.max(mapBounds.minLat, Math.min(mapBounds.maxLat, a.lat));\n");
      out.write("    a.lng = Math.max(mapBounds.minLng, Math.min(mapBounds.maxLng, a.lng));\n");
      out.write("  });\n");
      out.write("  drawMap();\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("function focusAmbulance(id) {\n");
      out.write("  const a = ambulances.find(x => x.id === id);\n");
      out.write("  if (a) {\n");
      out.write("    \n");
      out.write("    const pos = latLngToXY(a.lat, a.lng);\n");
      out.write("    ctx.beginPath();\n");
      out.write("    ctx.arc(pos.x, pos.y, 25, 0, Math.PI*2);\n");
      out.write("    ctx.strokeStyle = '#ef233c';\n");
      out.write("    ctx.lineWidth = 3;\n");
      out.write("    ctx.stroke();\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("\n");
      out.write("drawMap();\n");
      out.write("setInterval(updateAmbulances, 2000);\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
