/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-04-15 04:35:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.amritcare.dao.HospitalDAO;
import com.amritcare.dao.DoctorDAO;
import com.amritcare.model.*;
import java.util.*;

public final class booking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.amritcare.model");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.amritcare.dao.DoctorDAO");
    _jspx_imports_classes.add("com.amritcare.dao.HospitalDAO");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    if (session.getAttribute("loggedUser") == null) { response.sendRedirect("login.jsp"); return; }
    User loggedUser = (User) session.getAttribute("loggedUser");

    HospitalDAO hDao = new HospitalDAO();
    List<Hospital> hospitals = hDao.getAllHospitals();

    String preHospId = request.getParameter("hospitalId");
    String preType   = request.getParameter("type");
    Hospital preHosp = null;
    List<Doctor> preDoctors = new ArrayList<>();
    if (preHospId != null) {
        preHosp = hDao.getHospitalById(Integer.parseInt(preHospId));
        DoctorDAO dDao = new DoctorDAO();
        preDoctors = dDao.getAvailableDoctors(Integer.parseInt(preHospId));
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Book Appointment — AmritCare</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("  <style>\n");
      out.write("    .booking-tab {\n");
      out.write("      flex: 1; padding: 14px; text-align: center; border: 2px solid var(--border);\n");
      out.write("      border-radius: 10px; cursor: pointer; font-weight: 600; font-size: 0.95rem;\n");
      out.write("      transition: all 0.2s; background: var(--card); color: var(--text);\n");
      out.write("    }\n");
      out.write("    .booking-tab.active { background: var(--primary); color: #fff; border-color: var(--primary); }\n");
      out.write("    .booking-tab:hover:not(.active) { border-color: var(--primary); color: var(--primary); }\n");
      out.write("    .type-section { display: none; margin-top: 1rem; }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<nav class=\"navbar\">\n");
      out.write("  <a href=\"index.jsp\" class=\"navbar-brand\"><span class=\"logo-icon\">🏥</span> AmritCare</a>\n");
      out.write("  <ul class=\"nav-links\">\n");
      out.write("    <li><a href=\"index.jsp\">Home</a></li>\n");
      out.write("    <li><a href=\"HospitalServlet\">Hospitals</a></li>\n");
      out.write("    <li><a href=\"dashboard.jsp\">Dashboard</a></li>\n");
      out.write("    <li><a href=\"LogoutServlet\">Logout</a></li>\n");
      out.write("  </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div style=\"background:linear-gradient(135deg,var(--primary-dark),var(--primary));color:#fff;padding:2.5rem 2rem 2rem;\">\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <h1 style=\"font-family:'Playfair Display',serif;font-size:2rem\">📅 Book an Appointment</h1>\n");
      out.write("    <p style=\"opacity:0.85\">Select your booking type and fill in the details</p>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<section class=\"section\">\n");
      out.write("  <div class=\"container\" style=\"max-width:700px\">\n");
      out.write("\n");
      out.write("    <div class=\"card\">\n");
      out.write("      <div class=\"card-body\" style=\"padding:2rem\">\n");
      out.write("\n");
      out.write("       \n");
      out.write("        <div style=\"display:flex;gap:12px;margin-bottom:1.5rem\">\n");
      out.write("          <button class=\"booking-tab ");
      out.print( "Bed".equals(preType)||preType==null?"active":"" );
      out.write("\"\n");
      out.write("                  data-type=\"Bed\" onclick=\"switchTab('Bed')\">🛏 Book Bed</button>\n");
      out.write("          <button class=\"booking-tab ");
      out.print( "ICU".equals(preType)?"active":"" );
      out.write("\"\n");
      out.write("                  data-type=\"ICU\" onclick=\"switchTab('ICU')\">🏥 Book ICU</button>\n");
      out.write("          <button class=\"booking-tab ");
      out.print( "Doctor".equals(preType)?"active":"" );
      out.write("\"\n");
      out.write("                  data-type=\"Doctor\" onclick=\"switchTab('Doctor')\">👨‍⚕️ Doctor Appointment</button>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <form action=\"BookingServlet\" method=\"post\" onsubmit=\"return validateForm('bookingForm')\" id=\"bookingForm\">\n");
      out.write("          <input type=\"hidden\" name=\"bookingType\" id=\"bookingType\" value=\"");
      out.print( preType!=null?preType:"Bed" );
      out.write("\">\n");
      out.write("\n");
      out.write("         \n");
      out.write("          <div class=\"grid-2\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label>Patient Name <span style=\"color:var(--danger)\">*</span></label>\n");
      out.write("              <input type=\"text\" name=\"patientName\" class=\"form-control\" value=\"");
      out.print( loggedUser.getName() );
      out.write("\" required>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label>Contact Number <span style=\"color:var(--danger)\">*</span></label>\n");
      out.write("              <input type=\"tel\" name=\"contact\" class=\"form-control\"\n");
      out.write("                     value=\"");
      out.print( loggedUser.getPhone()!=null?loggedUser.getPhone():"" );
      out.write("\"\n");
      out.write("                     placeholder=\"10-digit mobile\" required maxlength=\"10\">\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label>Email Address <span style=\"color:var(--danger)\">*</span></label>\n");
      out.write("            <input type=\"email\" name=\"patientEmail\" class=\"form-control\" value=\"");
      out.print( loggedUser.getEmail() );
      out.write("\" required>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("       \n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label>Select Hospital <span style=\"color:var(--danger)\">*</span></label>\n");
      out.write("            <select name=\"hospitalId\" id=\"hospitalSelect\" class=\"form-control\" required\n");
      out.write("                    onchange=\"onHospitalChange(this.value)\">\n");
      out.write("              <option value=\"\">-- Select Hospital --</option>\n");
      out.write("              ");
 for (Hospital h : hospitals) { 
      out.write("\n");
      out.write("                <option value=\"");
      out.print( h.getId() );
      out.write('"');
      out.write(' ');
      out.print( (preHosp!=null&&h.getId()==preHosp.getId())?"selected":"" );
      out.write(">\n");
      out.write("                  ");
      out.print( h.getName() );
      out.write(" (Beds: ");
      out.print( h.getAvailableBeds() );
      out.write(", ICU: ");
      out.print( h.getAvailableIcu() );
      out.write(")\n");
      out.write("                </option>\n");
      out.write("              ");
 } 
      out.write("\n");
      out.write("            </select>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        \n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label>Booking Date <span style=\"color:var(--danger)\">*</span></label>\n");
      out.write("            <input type=\"date\" name=\"bookingDate\" class=\"form-control\" required\n");
      out.write("                   min=\"");
      out.print( new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()) );
      out.write("\">\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        \n");
      out.write("          <div class=\"type-section\" id=\"doctorSection\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label>Select Doctor <span style=\"color:var(--danger)\">*</span></label>\n");
      out.write("              <select name=\"doctorId\" id=\"doctorSelect\" class=\"form-control\">\n");
      out.write("                <option value=\"\">-- Select Hospital First --</option>\n");
      out.write("                ");
 for (Doctor d : preDoctors) { 
      out.write("\n");
      out.write("                  <option value=\"");
      out.print( d.getId() );
      out.write("\">\n");
      out.write("                    ");
      out.print( d.getName() );
      out.write(' ');
      out.write('—');
      out.write(' ');
      out.print( d.getSpecialization() );
      out.write(' ');
      out.write('(');
      out.print( d.getExperience() );
      out.write("y)\n");
      out.write("                  </option>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("              </select>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        \n");
      out.write("          <div class=\"type-section\" id=\"bedSection\">\n");
      out.write("            <div class=\"alert alert-info\">\n");
      out.write("              ℹ️ An available bed will be automatically assigned upon confirmation.\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("      \n");
      out.write("          <div class=\"type-section\" id=\"icuSection\">\n");
      out.write("            <div class=\"alert alert-warning\">\n");
      out.write("              ⚠️ ICU bookings are for critical care only. Our staff will verify and confirm.\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("     \n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label>Additional Notes (optional)</label>\n");
      out.write("            <textarea name=\"notes\" class=\"form-control\" rows=\"3\" placeholder=\"Any specific requirements or symptoms…\"></textarea>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <button type=\"submit\" class=\"btn btn-primary btn-lg\" style=\"width:100%;justify-content:center\">\n");
      out.write("            Confirm Booking ✓\n");
      out.write("          </button>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer><p>© 2026 AmritCare</p></footer>\n");
      out.write("<button class=\"voice-btn\" id=\"voiceBtn\" title=\"Voice Assistant\">🎤</button>\n");
      out.write("<div class=\"voice-tooltip\" id=\"voiceTooltip\"></div>\n");
      out.write("\n");
      out.write("<script src=\"js/main.js\"></script>\n");
      out.write("<script>\n");
      out.write("  function switchTab(type) {\n");
      out.write("    document.querySelectorAll('.booking-tab').forEach(t => t.classList.remove('active'));\n");
      out.write("    document.querySelector(`.booking-tab[data-type=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${type}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"]`).classList.add('active');\n");
      out.write("    document.getElementById('bookingType').value = type;\n");
      out.write("    document.getElementById('bedSection').style.display    = type==='Bed'    ? 'block':'none';\n");
      out.write("    document.getElementById('icuSection').style.display    = type==='ICU'    ? 'block':'none';\n");
      out.write("    document.getElementById('doctorSection').style.display = type==='Doctor' ? 'block':'none';\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  function onHospitalChange(hospitalId) {\n");
      out.write("    const type = document.getElementById('bookingType').value;\n");
      out.write("    if (type === 'Doctor' && hospitalId) loadDoctors(hospitalId);\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  // Init on load\n");
      out.write("  const initType = '");
      out.print( preType!=null?preType:"Bed" );
      out.write("';\n");
      out.write("  switchTab(initType);\n");
      out.write("  ");
 if (preHospId != null) { 
      out.write("\n");
      out.write("    if (initType === 'Doctor') loadDoctors('");
      out.print( preHospId );
      out.write("');\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
