/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-04-14 15:11:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.amritcare.dao.BookingDAO;
import com.amritcare.model.*;
import java.util.List;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.amritcare.model");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.amritcare.dao.BookingDAO");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    if (session.getAttribute("loggedUser") == null) { response.sendRedirect("login.jsp"); return; }
    User user = (User) session.getAttribute("loggedUser");
    if ("city_admin".equals(user.getRole()))     { response.sendRedirect("admin_dashboard.jsp"); return; }
    if ("hospital_admin".equals(user.getRole())) { response.sendRedirect("hospital_dashboard.jsp"); return; }

    BookingDAO dao = new BookingDAO();
    List<Booking> bookings = dao.getBookingsByEmail(user.getEmail());

    String success = (String) request.getAttribute("success");
    String error   = (String) request.getAttribute("error");

    
    long pending   = bookings.stream().filter(b->"pending".equals(b.getStatus())).count();
    long confirmed = bookings.stream().filter(b->"confirmed".equals(b.getStatus())).count();
    long completed = bookings.stream().filter(b->"completed".equals(b.getStatus())).count();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>My Dashboard — AmritCare</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<nav class=\"navbar\">\n");
      out.write("  <a href=\"index.jsp\" class=\"navbar-brand\"><span class=\"logo-icon\">🏥</span> AmritCare</a>\n");
      out.write("  <ul class=\"nav-links\">\n");
      out.write("    <li><a href=\"index.jsp\">Home</a></li>\n");
      out.write("    <li><a href=\"HospitalServlet\">Hospitals</a></li>\n");
      out.write("    <li><a href=\"booking.jsp\">Book</a></li>\n");
      out.write("    <li><a href=\"ambulance.jsp\">🚑</a></li>\n");
      out.write("    <li><a href=\"LogoutServlet\">Logout</a></li>\n");
      out.write("  </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"dashboard-layout\">\n");
      out.write("\n");
      out.write(" \n");
      out.write("  <aside class=\"sidebar\">\n");
      out.write("    <div class=\"sidebar-user\">\n");
      out.write("      <div class=\"avatar\">");
      out.print( user.getName().substring(0,1).toUpperCase() );
      out.write("</div>\n");
      out.write("      <div class=\"user-name\">");
      out.print( user.getName() );
      out.write("</div>\n");
      out.write("      <div class=\"user-role\">Patient</div>\n");
      out.write("    </div>\n");
      out.write("    <ul class=\"sidebar-nav\">\n");
      out.write("      <li><a href=\"dashboard.jsp\" class=\"active\"><span class=\"nav-icon\">📊</span> My Dashboard</a></li>\n");
      out.write("      <li><a href=\"HospitalServlet\"><span class=\"nav-icon\">🏥</span> Find Hospitals</a></li>\n");
      out.write("      <li><a href=\"booking.jsp?type=Bed\"><span class=\"nav-icon\">🛏</span> Book Bed</a></li>\n");
      out.write("      <li><a href=\"booking.jsp?type=ICU\"><span class=\"nav-icon\">🏥</span> Book ICU</a></li>\n");
      out.write("      <li><a href=\"booking.jsp?type=Doctor\"><span class=\"nav-icon\">👨‍⚕️</span> Book Doctor</a></li>\n");
      out.write("      <li><a href=\"ambulance.jsp\"><span class=\"nav-icon\">🚑</span> Ambulance</a></li>\n");
      out.write("      <li><a href=\"LogoutServlet\"><span class=\"nav-icon\">🚪</span> Logout</a></li>\n");
      out.write("    </ul>\n");
      out.write("  </aside>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <main class=\"dashboard-content\">\n");
      out.write("\n");
      out.write("    <div class=\"alert-container\">\n");
      out.write("      ");
 if (success!=null) { 
      out.write("<div class=\"alert alert-success\">✅ ");
      out.print( success );
      out.write("</div>");
 } 
      out.write("\n");
      out.write("      ");
 if (error!=null)   { 
      out.write("<div class=\"alert alert-danger\">❌ ");
      out.print( error );
      out.write("</div>");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div style=\"display:flex;align-items:center;justify-content:space-between;margin-bottom:1.5rem;flex-wrap:wrap;gap:1rem\">\n");
      out.write("      <div>\n");
      out.write("        <h1 style=\"font-family:'Playfair Display',serif;font-size:1.8rem\">Welcome, ");
      out.print( user.getName() );
      out.write("! 👋</h1>\n");
      out.write("        <p style=\"color:var(--muted)\">Manage your healthcare bookings</p>\n");
      out.write("      </div>\n");
      out.write("      <a href=\"booking.jsp\" class=\"btn btn-primary\">+ New Booking</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write(" \n");
      out.write("    <div class=\"grid-4\" style=\"margin-bottom:2rem\">\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon blue\">📅</div>\n");
      out.write("        <div>\n");
      out.write("          <div class=\"stat-value\">");
      out.print( bookings.size() );
      out.write("</div>\n");
      out.write("          <div class=\"stat-label\">Total Bookings</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon orange\">⏳</div>\n");
      out.write("        <div>\n");
      out.write("          <div class=\"stat-value\">");
      out.print( pending );
      out.write("</div>\n");
      out.write("          <div class=\"stat-label\">Pending</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon green\">✅</div>\n");
      out.write("        <div>\n");
      out.write("          <div class=\"stat-value\">");
      out.print( confirmed );
      out.write("</div>\n");
      out.write("          <div class=\"stat-label\">Confirmed</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon blue\">🏁</div>\n");
      out.write("        <div>\n");
      out.write("          <div class=\"stat-value\">");
      out.print( completed );
      out.write("</div>\n");
      out.write("          <div class=\"stat-label\">Completed</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <div class=\"card mb-3\">\n");
      out.write("      <div class=\"card-header\">\n");
      out.write("        <strong>⚡ Quick Actions</strong>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"card-body\" style=\"display:flex;gap:1rem;flex-wrap:wrap\">\n");
      out.write("        <a href=\"booking.jsp?type=Bed\"    class=\"btn btn-primary\">🛏 Book Bed</a>\n");
      out.write("        <a href=\"booking.jsp?type=ICU\"    class=\"btn btn-outline\">🏥 Book ICU</a>\n");
      out.write("        <a href=\"booking.jsp?type=Doctor\" class=\"btn btn-success\">👨‍⚕️ Doctor Appointment</a>\n");
      out.write("        <a href=\"ambulance.jsp\"           class=\"btn\" style=\"background:var(--warning);color:var(--text)\">🚑 Ambulance</a>\n");
      out.write("        <a href=\"HospitalServlet\"         class=\"btn btn-outline\">🏥 Find Hospitals</a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("   \n");
      out.write("    <div class=\"table-wrapper\">\n");
      out.write("      <div class=\"card-header\" style=\"padding:1rem 1.5rem\">\n");
      out.write("        <strong>📋 My Bookings</strong>\n");
      out.write("        <span style=\"font-size:0.82rem;color:var(--muted)\">");
      out.print( bookings.size() );
      out.write(" total</span>\n");
      out.write("      </div>\n");
      out.write("      ");
 if (bookings.isEmpty()) { 
      out.write("\n");
      out.write("        <div style=\"padding:3rem;text-align:center;color:var(--muted)\">\n");
      out.write("          <div style=\"font-size:3rem;margin-bottom:1rem\">📭</div>\n");
      out.write("          <p>No bookings yet. <a href=\"booking.jsp\" style=\"color:var(--primary)\">Make your first booking</a></p>\n");
      out.write("        </div>\n");
      out.write("      ");
 } else { 
      out.write("\n");
      out.write("      <table>\n");
      out.write("        <thead>\n");
      out.write("          <tr>\n");
      out.write("            <th>#</th>\n");
      out.write("            <th>Type</th>\n");
      out.write("            <th>Hospital</th>\n");
      out.write("            <th>Doctor</th>\n");
      out.write("            <th>Date</th>\n");
      out.write("            <th>Status</th>\n");
      out.write("          </tr>\n");
      out.write("        </thead>\n");
      out.write("        <tbody>\n");
      out.write("          ");
 for (Booking b : bookings) {
               String badgeCls = "badge-secondary";
               if ("confirmed".equals(b.getStatus())) badgeCls = "badge-success";
               else if ("pending".equals(b.getStatus())) badgeCls = "badge-warning";
               else if ("cancelled".equals(b.getStatus())) badgeCls = "badge-danger";
               else if ("completed".equals(b.getStatus())) badgeCls = "badge-info";
          
      out.write("\n");
      out.write("          <tr>\n");
      out.write("            <td><strong>#");
      out.print( b.getBookingId() );
      out.write("</strong></td>\n");
      out.write("            <td>\n");
      out.write("              ");
 if ("Bed".equals(b.getBookingType()))    out.print("🛏 Bed"); 
      out.write("\n");
      out.write("              ");
 if ("ICU".equals(b.getBookingType()))    out.print("🏥 ICU"); 
      out.write("\n");
      out.write("              ");
 if ("Doctor".equals(b.getBookingType())) out.print("👨‍⚕️ Doctor"); 
      out.write("\n");
      out.write("            </td>\n");
      out.write("            <td>");
      out.print( b.getHospitalName()!=null?b.getHospitalName():"—" );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( b.getDoctorName()!=null?b.getDoctorName():"—" );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( b.getBookingDate() );
      out.write("</td>\n");
      out.write("            <td><span class=\"badge ");
      out.print( badgeCls );
      out.write('"');
      out.write('>');
      out.print( b.getStatus().toUpperCase() );
      out.write("</span></td>\n");
      out.write("          </tr>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  </main>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<button class=\"voice-btn\" id=\"voiceBtn\" title=\"Voice Assistant\">🎤</button>\n");
      out.write("<div class=\"voice-tooltip\" id=\"voiceTooltip\"></div>\n");
      out.write("<script src=\"js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
