/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-04-14 09:10:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.amritcare.dao.*;
import com.amritcare.model.*;
import java.util.List;

public final class hospital_005fdashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.amritcare.model");
    _jspx_imports_packages.add("com.amritcare.dao");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    if (session.getAttribute("loggedUser")==null) { response.sendRedirect("login.jsp"); return; }
    User user = (User) session.getAttribute("loggedUser");
    if (!"hospital_admin".equals(user.getRole())) { response.sendRedirect("login.jsp"); return; }

    int hospitalId = user.getHospitalId();
    HospitalDAO hDao = new HospitalDAO();
    DoctorDAO   dDao = new DoctorDAO();
    BookingDAO  bDao = new BookingDAO();

    Hospital hospital = hDao.getHospitalById(hospitalId);
    List<Doctor>  doctors  = dDao.getDoctorsByHospital(hospitalId);
    List<Booking> bookings = bDao.getBookingsByHospital(hospitalId);

    long pendingCount = bookings.stream().filter(b->"pending".equals(b.getStatus())).count();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Hospital Dashboard — AmritCare</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<nav class=\"navbar\">\n");
      out.write("  <a href=\"index.jsp\" class=\"navbar-brand\"><span class=\"logo-icon\">🏥</span> AmritCare</a>\n");
      out.write("  <ul class=\"nav-links\">\n");
      out.write("    <li><a href=\"hospital_dashboard.jsp\" class=\"active\">Dashboard</a></li>\n");
      out.write("    <li><a href=\"manage_resources.jsp\">Resources</a></li>\n");
      out.write("    <li><a href=\"manage_doctors.jsp\">Doctors</a></li>\n");
      out.write("    <li><a href=\"LogoutServlet\">Logout</a></li>\n");
      out.write("  </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"dashboard-layout\">\n");
      out.write("\n");
      out.write("  <!-- Sidebar -->\n");
      out.write("  <aside class=\"sidebar\">\n");
      out.write("    <div class=\"sidebar-user\">\n");
      out.write("      <div class=\"avatar\">H</div>\n");
      out.write("      <div class=\"user-name\">");
      out.print( hospital!=null?hospital.getName():"Hospital" );
      out.write("</div>\n");
      out.write("      <div class=\"user-role\">Hospital Admin</div>\n");
      out.write("    </div>\n");
      out.write("    <ul class=\"sidebar-nav\">\n");
      out.write("      <li><a href=\"hospital_dashboard.jsp\" class=\"active\"><span class=\"nav-icon\">📊</span> Dashboard</a></li>\n");
      out.write("      <li><a href=\"manage_resources.jsp\"><span class=\"nav-icon\">🛏</span> Manage Resources</a></li>\n");
      out.write("      <li><a href=\"manage_doctors.jsp\"><span class=\"nav-icon\">👨‍⚕️</span> Manage Doctors</a></li>\n");
      out.write("      <li><a href=\"LogoutServlet\"><span class=\"nav-icon\">🚪</span> Logout</a></li>\n");
      out.write("    </ul>\n");
      out.write("  </aside>\n");
      out.write("\n");
      out.write("  <main class=\"dashboard-content\">\n");
      out.write("\n");
      out.write("    <div style=\"display:flex;align-items:center;justify-content:space-between;margin-bottom:1.5rem;flex-wrap:wrap;gap:1rem\">\n");
      out.write("      <div>\n");
      out.write("        <h1 style=\"font-family:'Playfair Display',serif;font-size:1.8rem\">\n");
      out.write("          🏥 ");
      out.print( hospital!=null?hospital.getName():"Hospital Dashboard" );
      out.write("\n");
      out.write("        </h1>\n");
      out.write("        <p style=\"color:var(--muted)\">");
      out.print( hospital!=null?hospital.getLocation():"" );
      out.write("</p>\n");
      out.write("      </div>\n");
      out.write("      ");
 if (pendingCount > 0) { 
      out.write("\n");
      out.write("        <div class=\"badge badge-warning\" style=\"font-size:0.9rem;padding:8px 16px\">\n");
      out.write("          ⚠️ ");
      out.print( pendingCount );
      out.write(" Pending Bookings\n");
      out.write("        </div>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Stats -->\n");
      out.write("    <div class=\"grid-4\" style=\"margin-bottom:2rem\">\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon blue\">📅</div>\n");
      out.write("        <div>\n");
      out.write("          <div class=\"stat-value\">");
      out.print( bookings.size() );
      out.write("</div>\n");
      out.write("          <div class=\"stat-label\">Total Bookings</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon orange\">⏳</div>\n");
      out.write("        <div>\n");
      out.write("          <div class=\"stat-value\">");
      out.print( pendingCount );
      out.write("</div>\n");
      out.write("          <div class=\"stat-label\">Pending</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon green\">👨‍⚕️</div>\n");
      out.write("        <div>\n");
      out.write("          <div class=\"stat-value\">");
      out.print( doctors.size() );
      out.write("</div>\n");
      out.write("          <div class=\"stat-label\">Doctors</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon blue\">⭐</div>\n");
      out.write("        <div>\n");
      out.write("          <div class=\"stat-value\">");
      out.print( hospital!=null?hospital.getRating():"—" );
      out.write("</div>\n");
      out.write("          <div class=\"stat-label\">Rating</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Doctors List -->\n");
      out.write("    <div class=\"table-wrapper mb-3\" style=\"margin-bottom:1.5rem\">\n");
      out.write("      <div class=\"card-header\">\n");
      out.write("        <strong>👨‍⚕️ Doctors</strong>\n");
      out.write("        <a href=\"manage_doctors.jsp\" class=\"btn btn-primary btn-sm\">Manage</a>\n");
      out.write("      </div>\n");
      out.write("      <table>\n");
      out.write("        <thead>\n");
      out.write("          <tr><th>Name</th><th>Specialization</th><th>Experience</th><th>Availability</th><th>Schedule</th></tr>\n");
      out.write("        </thead>\n");
      out.write("        <tbody>\n");
      out.write("          ");
 for (Doctor d : doctors) {
               String cls = "available".equals(d.getAvailability())?"badge-success":"badge-danger";
          
      out.write("\n");
      out.write("          <tr>\n");
      out.write("            <td><strong>Dr. ");
      out.print( d.getName() );
      out.write("</strong></td>\n");
      out.write("            <td>");
      out.print( d.getSpecialization() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( d.getExperience() );
      out.write(" yrs</td>\n");
      out.write("            <td><span class=\"badge ");
      out.print( cls );
      out.write('"');
      out.write('>');
      out.print( d.getAvailability().toUpperCase() );
      out.write("</span></td>\n");
      out.write("            <td style=\"font-size:0.82rem;color:var(--muted)\">");
      out.print( d.getSchedule() );
      out.write("</td>\n");
      out.write("          </tr>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("          ");
 if (doctors.isEmpty()) { 
      out.write("\n");
      out.write("          <tr><td colspan=\"5\" style=\"text-align:center;color:var(--muted);padding:2rem\">No doctors listed. <a href=\"manage_doctors.jsp\">Add doctors</a></td></tr>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Bookings -->\n");
      out.write("    <div class=\"table-wrapper\">\n");
      out.write("      <div class=\"card-header\">\n");
      out.write("        <strong>📋 Patient Bookings</strong>\n");
      out.write("      </div>\n");
      out.write("      <table>\n");
      out.write("        <thead>\n");
      out.write("          <tr><th>#</th><th>Patient</th><th>Type</th><th>Date</th><th>Contact</th><th>Status</th><th>Action</th></tr>\n");
      out.write("        </thead>\n");
      out.write("        <tbody>\n");
      out.write("          ");
 for (Booking b : bookings) {
               String badgeCls = "badge-secondary";
               if ("confirmed".equals(b.getStatus())) badgeCls = "badge-success";
               else if ("pending".equals(b.getStatus())) badgeCls = "badge-warning";
               else if ("cancelled".equals(b.getStatus())) badgeCls = "badge-danger";
          
      out.write("\n");
      out.write("          <tr>\n");
      out.write("            <td>#");
      out.print( b.getBookingId() );
      out.write("</td>\n");
      out.write("            <td><strong>");
      out.print( b.getPatientName() );
      out.write("</strong><br><small style=\"color:var(--muted)\">");
      out.print( b.getPatientEmail() );
      out.write("</small></td>\n");
      out.write("            <td>");
      out.print( b.getBookingType() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( b.getBookingDate() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( b.getContact() );
      out.write("</td>\n");
      out.write("            <td><span class=\"badge ");
      out.print( badgeCls );
      out.write('"');
      out.write('>');
      out.print( b.getStatus().toUpperCase() );
      out.write("</span></td>\n");
      out.write("            <td>\n");
      out.write("              ");
 if ("pending".equals(b.getStatus())) { 
      out.write("\n");
      out.write("                <a href=\"BookingServlet?action=updateStatus&id=");
      out.print( b.getBookingId() );
      out.write("&status=confirmed\"\n");
      out.write("                   class=\"btn btn-success btn-sm\">✓ Confirm</a>\n");
      out.write("                <a href=\"BookingServlet?action=updateStatus&id=");
      out.print( b.getBookingId() );
      out.write("&status=cancelled\"\n");
      out.write("                   class=\"btn btn-danger btn-sm\">✗ Cancel</a>\n");
      out.write("              ");
 } else if ("confirmed".equals(b.getStatus())) { 
      out.write("\n");
      out.write("                <a href=\"BookingServlet?action=updateStatus&id=");
      out.print( b.getBookingId() );
      out.write("&status=completed\"\n");
      out.write("                   class=\"btn btn-sm\" style=\"background:var(--accent);color:#fff\">✓ Complete</a>\n");
      out.write("              ");
 } 
      out.write("\n");
      out.write("            </td>\n");
      out.write("          </tr>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("          ");
 if (bookings.isEmpty()) { 
      out.write("\n");
      out.write("          <tr><td colspan=\"7\" style=\"text-align:center;color:var(--muted);padding:2rem\">No bookings yet</td></tr>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  </main>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<button class=\"voice-btn\" id=\"voiceBtn\">🎤</button>\n");
      out.write("<div class=\"voice-tooltip\" id=\"voiceTooltip\"></div>\n");
      out.write("<script src=\"js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
