/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-04-14 09:01:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.amritcare.dao.HospitalDAO;
import com.amritcare.model.Hospital;
import java.util.List;

public final class hospitals_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.amritcare.dao.HospitalDAO");
    _jspx_imports_classes.add("com.amritcare.model.Hospital");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    HospitalDAO dao = new HospitalDAO();
    List<Hospital> hospitals = dao.getAllHospitals();
    String userName = (String) session.getAttribute("userName");
    String userRole = (String) session.getAttribute("userRole");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Hospitals — AmritCare</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<nav class=\"navbar\">\n");
      out.write("  <a href=\"index.jsp\" class=\"navbar-brand\"><span class=\"logo-icon\">🏥</span> AmritCare</a>\n");
      out.write("  <ul class=\"nav-links\">\n");
      out.write("    <li><a href=\"index.jsp\">Home</a></li>\n");
      out.write("    <li><a href=\"HospitalServlet\" class=\"active\">Hospitals</a></li>\n");
      out.write("    <li><a href=\"ambulance.jsp\">🚑 Ambulance</a></li>\n");
      out.write("    ");
 if (userName != null) { 
      out.write("\n");
      out.write("      <li><a href=\"dashboard.jsp\">Dashboard</a></li>\n");
      out.write("      <li><a href=\"LogoutServlet\">Logout</a></li>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("      <li><a href=\"login.jsp\">Login</a></li>\n");
      out.write("      <li><a href=\"register.jsp\" class=\"btn-nav\">Register</a></li>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<!-- Page Header -->\n");
      out.write("<div style=\"background:linear-gradient(135deg,var(--primary-dark),var(--primary));color:#fff;padding:3rem 2rem 2rem;\">\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <h1 style=\"font-family:'Playfair Display',serif;font-size:2rem;margin-bottom:0.5rem\">🏥 Find Hospitals</h1>\n");
      out.write("    <p style=\"opacity:0.85\">Real-time availability across ");
      out.print( hospitals.size() );
      out.write(" partner hospitals in Bhopal</p>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<section class=\"section\">\n");
      out.write("  <div class=\"container\">\n");
      out.write("\n");
      out.write("    <!-- Search Bar -->\n");
      out.write("    <div class=\"search-bar\">\n");
      out.write("      <input type=\"text\" id=\"hospitalSearch\" placeholder=\"🔍 Search by name, location or specialization…\" class=\"form-control\" style=\"flex:1\">\n");
      out.write("      <button class=\"btn btn-primary\" onclick=\"document.getElementById('hospitalSearch').dispatchEvent(new Event('input'))\">Search</button>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Filter Tags -->\n");
      out.write("    <div style=\"display:flex;gap:8px;flex-wrap:wrap;margin-bottom:2rem;\">\n");
      out.write("      <span style=\"font-size:0.85rem;color:var(--muted);align-self:center;\">Quick filters:</span>\n");
      out.write("      ");
 String[] filters = {"Cardiology","Neurology","Orthopaedics","Gynaecology","Oncology","ICU"}; 
      out.write("\n");
      out.write("      ");
 for (String f : filters) { 
      out.write("\n");
      out.write("        <button class=\"btn btn-outline btn-sm\" onclick=\"document.getElementById('hospitalSearch').value='");
      out.print( f );
      out.write("';document.getElementById('hospitalSearch').dispatchEvent(new Event('input'))\">");
      out.print( f );
      out.write("</button>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("      <button class=\"btn btn-sm\" style=\"background:var(--bg);color:var(--muted)\" onclick=\"document.getElementById('hospitalSearch').value='';document.getElementById('hospitalSearch').dispatchEvent(new Event('input'))\">Clear</button>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Hospital Grid -->\n");
      out.write("    <div class=\"grid-3\" id=\"hospitalsGrid\">\n");
      out.write("      ");

        for (Hospital h : hospitals) {
          String[] specs = (h.getSpecialization() != null ? h.getSpecialization() : "").split(",");
      
      out.write("\n");
      out.write("      <div class=\"hospital-card fade-in\">\n");
      out.write("        <div class=\"hcard-header\">\n");
      out.write("          <div>\n");
      out.write("            <div class=\"hcard-name\">🏥 ");
      out.print( h.getName() );
      out.write("</div>\n");
      out.write("            <div class=\"hcard-loc\">📍 ");
      out.print( h.getLocation() );
      out.write("</div>\n");
      out.write("          </div>\n");
      out.write("          <div>\n");
      out.write("            <div class=\"rating-stars\" style=\"font-size:0.85rem\">\n");
      out.write("              ");

                double r = h.getRating();
                int full = (int)r;
                for (int i=0;i<full;i++) out.print("★");
                for (int i=full;i<5;i++) out.print("☆");
              
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <small style=\"opacity:0.8\">");
      out.print( h.getRating() );
      out.write("/5</small>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"hcard-body\">\n");
      out.write("          <div class=\"specialization-tags\">\n");
      out.write("            ");
 for (int i=0; i<Math.min(specs.length,3); i++) { 
      out.write("\n");
      out.write("              <span class=\"spec-tag\">");
      out.print( specs[i].trim() );
      out.write("</span>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("          </div>\n");
      out.write("          <div class=\"resource-badges\">\n");
      out.write("            <div class=\"resource-badge\">\n");
      out.write("              <div class=\"rb-count\" style=\"color:");
      out.print( h.getAvailableBeds()>0?"var(--success)":"var(--danger)" );
      out.write("\">\n");
      out.write("                ");
      out.print( h.getAvailableBeds() );
      out.write("\n");
      out.write("              </div>\n");
      out.write("              <div class=\"rb-label\">Beds</div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"resource-badge\">\n");
      out.write("              <div class=\"rb-count\" style=\"color:");
      out.print( h.getAvailableIcu()>0?"var(--primary)":"var(--danger)" );
      out.write("\">\n");
      out.write("                ");
      out.print( h.getAvailableIcu() );
      out.write("\n");
      out.write("              </div>\n");
      out.write("              <div class=\"rb-label\">ICU</div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"resource-badge\">\n");
      out.write("              <div class=\"rb-count\" style=\"color:");
      out.print( h.getAvailableDoctors()>0?"var(--success)":"var(--danger)" );
      out.write("\">\n");
      out.write("                ");
      out.print( h.getAvailableDoctors() );
      out.write("\n");
      out.write("              </div>\n");
      out.write("              <div class=\"rb-label\">Doctors</div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <p style=\"font-size:0.83rem;color:var(--muted);margin-top:0.5rem\">📞 ");
      out.print( h.getContact() );
      out.write("</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"hcard-actions\">\n");
      out.write("          <a href=\"booking.jsp?hospitalId=");
      out.print( h.getId() );
      out.write("&type=Bed\"\n");
      out.write("             class=\"btn btn-primary btn-sm\" style=\"");
      out.print( h.getAvailableBeds()==0?"opacity:0.5;cursor:not-allowed":"" );
      out.write("\">\n");
      out.write("            🛏 Bed\n");
      out.write("          </a>\n");
      out.write("          <a href=\"booking.jsp?hospitalId=");
      out.print( h.getId() );
      out.write("&type=ICU\"\n");
      out.write("             class=\"btn btn-outline btn-sm\" style=\"");
      out.print( h.getAvailableIcu()==0?"opacity:0.5;cursor:not-allowed":"" );
      out.write("\">\n");
      out.write("            🏥 ICU\n");
      out.write("          </a>\n");
      out.write("          <a href=\"booking.jsp?hospitalId=");
      out.print( h.getId() );
      out.write("&type=Doctor\"\n");
      out.write("             class=\"btn btn-success btn-sm\" style=\"");
      out.print( h.getAvailableDoctors()==0?"opacity:0.5;cursor:not-allowed":"" );
      out.write("\">\n");
      out.write("            👨‍⚕️ Doctor\n");
      out.write("          </a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer><p>© 2026 AmritCare — Smart Healthcare, Bhopal</p></footer>\n");
      out.write("<button class=\"voice-btn\" id=\"voiceBtn\" title=\"Voice Assistant\">🎤</button>\n");
      out.write("<div class=\"voice-tooltip\" id=\"voiceTooltip\"></div>\n");
      out.write("<script src=\"js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
