/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-04-14 09:01:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.amritcare.dao.HospitalDAO;
import com.amritcare.dao.BookingDAO;
import com.amritcare.dao.UserDAO;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.amritcare.dao.UserDAO");
    _jspx_imports_classes.add("com.amritcare.dao.HospitalDAO");
    _jspx_imports_classes.add("com.amritcare.dao.BookingDAO");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    HospitalDAO hDao = new HospitalDAO();
    BookingDAO  bDao = new BookingDAO();
    UserDAO     uDao = new UserDAO();
    int totalHospitals = hDao.getTotalHospitals();
    int totalBookings  = bDao.getTotalBookings();
    int totalPatients  = uDao.getTotalPatients();
    String userName = (String) session.getAttribute("userName");
    String userRole = (String) session.getAttribute("userRole");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>AmritCare — Smart Healthcare Management</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!-- NAVBAR -->\n");
      out.write("<nav class=\"navbar\">\n");
      out.write("  <a href=\"index.jsp\" class=\"navbar-brand\">\n");
      out.write("    <span class=\"logo-icon\">🏥</span> AmritCare\n");
      out.write("  </a>\n");
      out.write("  <ul class=\"nav-links\">\n");
      out.write("    <li><a href=\"index.jsp\" class=\"active\">Home</a></li>\n");
      out.write("    <li><a href=\"HospitalServlet\">Hospitals</a></li>\n");
      out.write("    <li><a href=\"ambulance.jsp\">🚑 Ambulance</a></li>\n");
      out.write("    ");
 if (userName != null) { 
      out.write("\n");
      out.write("      ");
 if ("city_admin".equals(userRole)) { 
      out.write("\n");
      out.write("        <li><a href=\"admin_dashboard.jsp\">Dashboard</a></li>\n");
      out.write("      ");
 } else if ("hospital_admin".equals(userRole)) { 
      out.write("\n");
      out.write("        <li><a href=\"hospital_dashboard.jsp\">Dashboard</a></li>\n");
      out.write("      ");
 } else { 
      out.write("\n");
      out.write("        <li><a href=\"dashboard.jsp\">Dashboard</a></li>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("      <li><a href=\"LogoutServlet\">Logout</a></li>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("      <li><a href=\"login.jsp\">Login</a></li>\n");
      out.write("      <li><a href=\"register.jsp\" class=\"btn-nav\">Register</a></li>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<!-- HERO -->\n");
      out.write("<section class=\"hero\">\n");
      out.write("  <h1 class=\"hero-title\">City-Wide Smart<br>Healthcare, Unified</h1>\n");
      out.write("  <p class=\"hero-subtitle\">Real-time hospital availability, instant bookings, ambulance tracking — all in one platform for Bhopal.</p>\n");
      out.write("  <div class=\"hero-actions\">\n");
      out.write("    <a href=\"HospitalServlet\" class=\"btn btn-white\">🏥 Find Hospitals</a>\n");
      out.write("    <a href=\"register.jsp\"    class=\"btn btn-white btn-outline\" style=\"border-color:#fff;color:#fff\">Get Started Free</a>\n");
      out.write("    <a href=\"ambulance.jsp\"   class=\"btn\" style=\"background:var(--warning);color:#1a1a2e\">🚑 Track Ambulance</a>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- STATS -->\n");
      out.write("<section class=\"section\" style=\"background:#fff; padding: 2.5rem 0;\">\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <div class=\"grid-4\">\n");
      out.write("      <div class=\"stat-card fade-in delay-1\">\n");
      out.write("        <div class=\"stat-icon blue\">🏥</div>\n");
      out.write("        <div>\n");
      out.write("          <div class=\"stat-value\" data-target=\"");
      out.print( totalHospitals );
      out.write('"');
      out.write('>');
      out.print( totalHospitals );
      out.write("</div>\n");
      out.write("          <div class=\"stat-label\">Partner Hospitals</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card fade-in delay-2\">\n");
      out.write("        <div class=\"stat-icon green\">✅</div>\n");
      out.write("        <div>\n");
      out.write("          <div class=\"stat-value\" data-target=\"");
      out.print( totalBookings );
      out.write('"');
      out.write('>');
      out.print( totalBookings );
      out.write("</div>\n");
      out.write("          <div class=\"stat-label\">Bookings Made</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card fade-in delay-3\">\n");
      out.write("        <div class=\"stat-icon orange\">👨‍⚕️</div>\n");
      out.write("        <div>\n");
      out.write("          <div class=\"stat-value\" data-target=\"");
      out.print( totalPatients );
      out.write('"');
      out.write('>');
      out.print( totalPatients );
      out.write("</div>\n");
      out.write("          <div class=\"stat-label\">Registered Patients</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card fade-in\">\n");
      out.write("        <div class=\"stat-icon red\">🚑</div>\n");
      out.write("        <div>\n");
      out.write("          <div class=\"stat-value\">5</div>\n");
      out.write("          <div class=\"stat-label\">Active Ambulances</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- FEATURES -->\n");
      out.write("<section class=\"section\">\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <h2 class=\"section-title text-center\">Why AmritCare?</h2>\n");
      out.write("    <p class=\"section-subtitle text-center\">Everything a patient needs, at a glance</p>\n");
      out.write("    <div class=\"grid-3\">\n");
      out.write("      <div class=\"card fade-in\">\n");
      out.write("        <div class=\"card-body\" style=\"text-align:center; padding:2.5rem 1.5rem;\">\n");
      out.write("          <div style=\"font-size:3rem;margin-bottom:1rem\">📊</div>\n");
      out.write("          <h3 style=\"font-family:'Playfair Display',serif;margin-bottom:0.75rem\">Real-Time Availability</h3>\n");
      out.write("          <p style=\"color:var(--muted);font-size:0.9rem\">See live bed, ICU and doctor availability across all city hospitals before you travel.</p>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"card fade-in delay-1\">\n");
      out.write("        <div class=\"card-body\" style=\"text-align:center; padding:2.5rem 1.5rem;\">\n");
      out.write("          <div style=\"font-size:3rem;margin-bottom:1rem\">📅</div>\n");
      out.write("          <h3 style=\"font-family:'Playfair Display',serif;margin-bottom:0.75rem\">Instant Booking</h3>\n");
      out.write("          <p style=\"color:var(--muted);font-size:0.9rem\">Book a bed, ICU slot or doctor appointment in under 60 seconds with full confirmation.</p>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"card fade-in delay-2\">\n");
      out.write("        <div class=\"card-body\" style=\"text-align:center; padding:2.5rem 1.5rem;\">\n");
      out.write("          <div style=\"font-size:3rem;margin-bottom:1rem\">🚑</div>\n");
      out.write("          <h3 style=\"font-family:'Playfair Display',serif;margin-bottom:0.75rem\">Ambulance Tracking</h3>\n");
      out.write("          <p style=\"color:var(--muted);font-size:0.9rem\">Live map tracking of all city ambulances with nearest hospital routing.</p>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"card fade-in\">\n");
      out.write("        <div class=\"card-body\" style=\"text-align:center; padding:2.5rem 1.5rem;\">\n");
      out.write("          <div style=\"font-size:3rem;margin-bottom:1rem\">🎤</div>\n");
      out.write("          <h3 style=\"font-family:'Playfair Display',serif;margin-bottom:0.75rem\">Voice Assistant</h3>\n");
      out.write("          <p style=\"color:var(--muted);font-size:0.9rem\">Use voice commands like \"book bed\" or \"show hospitals\" to navigate hands-free.</p>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"card fade-in delay-1\">\n");
      out.write("        <div class=\"card-body\" style=\"text-align:center; padding:2.5rem 1.5rem;\">\n");
      out.write("          <div style=\"font-size:3rem;margin-bottom:1rem\">🔐</div>\n");
      out.write("          <h3 style=\"font-family:'Playfair Display',serif;margin-bottom:0.75rem\">Role-Based Access</h3>\n");
      out.write("          <p style=\"color:var(--muted);font-size:0.9rem\">Separate dashboards for patients, hospital admins and city authorities.</p>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"card fade-in delay-2\">\n");
      out.write("        <div class=\"card-body\" style=\"text-align:center; padding:2.5rem 1.5rem;\">\n");
      out.write("          <div style=\"font-size:3rem;margin-bottom:1rem\">📈</div>\n");
      out.write("          <h3 style=\"font-family:'Playfair Display',serif;margin-bottom:0.75rem\">Analytics & Reports</h3>\n");
      out.write("          <p style=\"color:var(--muted);font-size:0.9rem\">City admins get full analytics on utilization, bookings and resource distribution.</p>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- CTA -->\n");
      out.write("<section style=\"background:linear-gradient(135deg,var(--primary-dark),var(--primary));color:#fff;padding:4rem 2rem;text-align:center;\">\n");
      out.write("  <h2 style=\"font-family:'Playfair Display',serif;font-size:2rem;margin-bottom:1rem\">Ready to experience smarter healthcare?</h2>\n");
      out.write("  <p style=\"opacity:0.85;margin-bottom:2rem;max-width:500px;margin-left:auto;margin-right:auto\">Join thousands of patients and hospitals already using AmritCare.</p>\n");
      out.write("  <a href=\"register.jsp\" class=\"btn btn-white btn-lg\">Create Free Account →</a>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- FOOTER -->\n");
      out.write("<footer>\n");
      out.write("  <p>© 2026 AmritCare — Intelligent City-Wide Healthcare System | Bhopal, Madhya Pradesh</p>\n");
      out.write("  <p style=\"margin-top:0.5rem\"><a href=\"index.jsp\">Home</a> · <a href=\"HospitalServlet\">Hospitals</a> · <a href=\"ambulance.jsp\">Ambulance</a> · <a href=\"login.jsp\">Login</a></p>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<!-- VOICE ASSISTANT -->\n");
      out.write("<button class=\"voice-btn\" id=\"voiceBtn\" title=\"Voice Assistant\">🎤</button>\n");
      out.write("<div class=\"voice-tooltip\" id=\"voiceTooltip\"></div>\n");
      out.write("\n");
      out.write("<script src=\"js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
