/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-04-14 15:08:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    // Redirect if already logged in
    if (session.getAttribute("loggedUser") != null) {
        String role = (String) session.getAttribute("userRole");
        if ("city_admin".equals(role)) response.sendRedirect("admin_dashboard.jsp");
        else if ("hospital_admin".equals(role)) response.sendRedirect("hospital_dashboard.jsp");
        else response.sendRedirect("dashboard.jsp");
        return;
    }
    String error   = (String) request.getAttribute("error");
    String success = (String) request.getAttribute("success");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Login — AmritCare</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("  <style>\n");
      out.write("    body { display:flex; flex-direction:column; min-height:100vh; }\n");
      out.write("    .login-wrap { flex:1; display:flex; align-items:center; justify-content:center; padding:3rem 1rem; }\n");
      out.write("    .form-card { width:100%; }\n");
      out.write("    .demo-box { background:rgba(0,119,182,0.06); border-radius:10px; padding:1rem 1.25rem; margin-top:1.5rem; font-size:0.82rem; color:var(--muted); }\n");
      out.write("    .demo-box strong { color:var(--primary-dark); }\n");
      out.write("    .demo-row { display:flex; justify-content:space-between; margin-top:4px; }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<nav class=\"navbar\">\n");
      out.write("  <a href=\"index.jsp\" class=\"navbar-brand\"><span class=\"logo-icon\">🏥</span> AmritCare</a>\n");
      out.write("  <ul class=\"nav-links\">\n");
      out.write("    <li><a href=\"index.jsp\">Home</a></li>\n");
      out.write("    <li><a href=\"register.jsp\" class=\"btn-nav\">Register</a></li>\n");
      out.write("  </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"login-wrap\">\n");
      out.write("  <div class=\"form-card\" style=\"max-width:440px\">\n");
      out.write("    <div style=\"text-align:center;margin-bottom:2rem\">\n");
      out.write("      <div style=\"font-size:3rem\">🏥</div>\n");
      out.write("      <h1 class=\"form-title\">Welcome Back</h1>\n");
      out.write("      <p style=\"color:var(--muted);font-size:0.9rem\">Sign in to your AmritCare account</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
 if (error != null) { 
      out.write("\n");
      out.write("      <div class=\"alert alert-danger\">❌ ");
      out.print( error );
      out.write("</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    ");
 if (success != null) { 
      out.write("\n");
      out.write("      <div class=\"alert alert-success\">✅ ");
      out.print( success );
      out.write("</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <form action=\"LoginServlet\" method=\"post\" onsubmit=\"return validateForm('loginForm')\" id=\"loginForm\">\n");
      out.write("      <div class=\"form-group\">\n");
      out.write("        <label>Email Address</label>\n");
      out.write("        <input type=\"email\" name=\"email\" class=\"form-control\" placeholder=\"you@example.com\" required>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"form-group\">\n");
      out.write("        <label>Password</label>\n");
      out.write("        <input type=\"password\" name=\"password\" class=\"form-control\" placeholder=\"Your password\" required>\n");
      out.write("      </div>\n");
      out.write("      <button type=\"submit\" class=\"btn btn-primary\" style=\"width:100%;margin-top:0.5rem;justify-content:center\">\n");
      out.write("        Sign In →\n");
      out.write("      </button>\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <p style=\"text-align:center;margin-top:1.25rem;font-size:0.9rem;color:var(--muted)\">\n");
      out.write("      No account? <a href=\"register.jsp\" style=\"color:var(--primary);font-weight:600\">Register here</a>\n");
      out.write("    </p>\n");
      out.write("\n");
      out.write("    \n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<footer><p>© 2026 AmritCare</p></footer>\n");
      out.write("<button class=\"voice-btn\" id=\"voiceBtn\" title=\"Voice Assistant\">🎤</button>\n");
      out.write("<div class=\"voice-tooltip\" id=\"voiceTooltip\"></div>\n");
      out.write("<script src=\"js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
