/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-04-14 09:10:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.amritcare.model.*;
import com.amritcare.util.DBConnection;
import java.sql.*;
import java.util.*;

public final class manage_005fresources_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.amritcare.model");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.amritcare.util.DBConnection");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    if (session.getAttribute("loggedUser")==null) { response.sendRedirect("login.jsp"); return; }
    User user = (User) session.getAttribute("loggedUser");
    if (!"hospital_admin".equals(user.getRole())) { response.sendRedirect("login.jsp"); return; }

    int hospitalId = user.getHospitalId();
    String msg = "", msgType = "success";

    // Handle status update
    String updateType = request.getParameter("updateType");
    String unitId     = request.getParameter("unitId");
    String newStatus  = request.getParameter("status");

    if (updateType != null && unitId != null && newStatus != null) {
        String table = "bed".equals(updateType) ? "bed" : "icu";
        String sql   = "UPDATE " + table + " SET status=? WHERE id=? AND hospital_id=?";
        try (Connection con = DBConnection.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, newStatus);
            ps.setInt(2, Integer.parseInt(unitId));
            ps.setInt(3, hospitalId);
            ps.executeUpdate();
            msg = "Status updated successfully!";
        } catch (Exception e) { msg = "Update failed: " + e.getMessage(); msgType = "danger"; }
    }

    // Load beds
    List<Map<String,String>> beds = new ArrayList<>();
    try (Connection con = DBConnection.getConnection();
         PreparedStatement ps = con.prepareStatement("SELECT * FROM bed WHERE hospital_id=? ORDER BY bed_number")) {
        ps.setInt(1, hospitalId);
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            Map<String,String> m = new LinkedHashMap<>();
            m.put("id", rs.getString("id"));
            m.put("number", rs.getString("bed_number"));
            m.put("type", rs.getString("type"));
            m.put("status", rs.getString("status"));
            beds.add(m);
        }
    } catch (Exception e) { e.printStackTrace(); }

    // Load ICU units
    List<Map<String,String>> icus = new ArrayList<>();
    try (Connection con = DBConnection.getConnection();
         PreparedStatement ps = con.prepareStatement("SELECT * FROM icu WHERE hospital_id=? ORDER BY unit_number")) {
        ps.setInt(1, hospitalId);
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            Map<String,String> m = new LinkedHashMap<>();
            m.put("id", rs.getString("id"));
            m.put("number", rs.getString("unit_number"));
            m.put("status", rs.getString("status"));
            icus.add(m);
        }
    } catch (Exception e) { e.printStackTrace(); }

    long availBeds = beds.stream().filter(b->"available".equals(b.get("status"))).count();
    long availIcus = icus.stream().filter(i->"available".equals(i.get("status"))).count();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Manage Resources — AmritCare</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("  <style>\n");
      out.write("    .unit-grid { display:grid; grid-template-columns: repeat(auto-fill,minmax(160px,1fr)); gap:0.75rem; }\n");
      out.write("    .unit-card {\n");
      out.write("      background:var(--card); border-radius:12px; padding:1rem; text-align:center;\n");
      out.write("      border:2px solid var(--border); transition:all 0.2s;\n");
      out.write("    }\n");
      out.write("    .unit-card.available { border-color:var(--success); background:rgba(6,214,160,0.05); }\n");
      out.write("    .unit-card.occupied  { border-color:var(--danger);  background:rgba(239,35,60,0.05); }\n");
      out.write("    .unit-card.maintenance { border-color:var(--warning); background:rgba(255,209,102,0.08); }\n");
      out.write("    .unit-number { font-size:1.1rem; font-weight:700; margin-bottom:0.5rem; }\n");
      out.write("    .unit-status { font-size:0.75rem; text-transform:uppercase; letter-spacing:0.5px; margin-bottom:0.75rem; }\n");
      out.write("    .unit-actions select { font-size:0.8rem; padding:4px 8px; border-radius:6px; border:1px solid var(--border); }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<nav class=\"navbar\">\n");
      out.write("  <a href=\"index.jsp\" class=\"navbar-brand\"><span class=\"logo-icon\">🏥</span> AmritCare</a>\n");
      out.write("  <ul class=\"nav-links\">\n");
      out.write("    <li><a href=\"hospital_dashboard.jsp\">Dashboard</a></li>\n");
      out.write("    <li><a href=\"manage_resources.jsp\" class=\"active\">Resources</a></li>\n");
      out.write("    <li><a href=\"manage_doctors.jsp\">Doctors</a></li>\n");
      out.write("    <li><a href=\"LogoutServlet\">Logout</a></li>\n");
      out.write("  </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"dashboard-layout\">\n");
      out.write("  <aside class=\"sidebar\">\n");
      out.write("    <div class=\"sidebar-user\">\n");
      out.write("      <div class=\"avatar\">H</div>\n");
      out.write("      <div class=\"user-name\">Hospital Admin</div>\n");
      out.write("      <div class=\"user-role\">Staff</div>\n");
      out.write("    </div>\n");
      out.write("    <ul class=\"sidebar-nav\">\n");
      out.write("      <li><a href=\"hospital_dashboard.jsp\"><span class=\"nav-icon\">📊</span> Dashboard</a></li>\n");
      out.write("      <li><a href=\"manage_resources.jsp\" class=\"active\"><span class=\"nav-icon\">🛏</span> Resources</a></li>\n");
      out.write("      <li><a href=\"manage_doctors.jsp\"><span class=\"nav-icon\">👨‍⚕️</span> Doctors</a></li>\n");
      out.write("      <li><a href=\"LogoutServlet\"><span class=\"nav-icon\">🚪</span> Logout</a></li>\n");
      out.write("    </ul>\n");
      out.write("  </aside>\n");
      out.write("\n");
      out.write("  <main class=\"dashboard-content\">\n");
      out.write("\n");
      out.write("    <h1 style=\"font-family:'Playfair Display',serif;margin-bottom:1.5rem\">🛏 Resource Management</h1>\n");
      out.write("\n");
      out.write("    ");
 if (!msg.isEmpty()) { 
      out.write("\n");
      out.write("      <div class=\"alert alert-");
      out.print( msgType );
      out.write('"');
      out.write('>');
      out.print( msg );
      out.write("</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Summary Stats -->\n");
      out.write("    <div class=\"grid-4\" style=\"margin-bottom:2rem\">\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon green\">🛏</div>\n");
      out.write("        <div><div class=\"stat-value\">");
      out.print( availBeds );
      out.write("</div><div class=\"stat-label\">Available Beds</div></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon red\">🛏</div>\n");
      out.write("        <div><div class=\"stat-value\">");
      out.print( beds.size()-availBeds );
      out.write("</div><div class=\"stat-label\">Occupied Beds</div></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon green\">🏥</div>\n");
      out.write("        <div><div class=\"stat-value\">");
      out.print( availIcus );
      out.write("</div><div class=\"stat-label\">Available ICU</div></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon red\">🏥</div>\n");
      out.write("        <div><div class=\"stat-value\">");
      out.print( icus.size()-availIcus );
      out.write("</div><div class=\"stat-label\">Occupied ICU</div></div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Beds -->\n");
      out.write("    <div class=\"card mb-3\" style=\"margin-bottom:1.5rem\">\n");
      out.write("      <div class=\"card-header\"><strong>🛏 Beds (");
      out.print( beds.size() );
      out.write(" total, ");
      out.print( availBeds );
      out.write(" available)</strong></div>\n");
      out.write("      <div class=\"card-body\">\n");
      out.write("        <div class=\"unit-grid\">\n");
      out.write("          ");
 for (Map<String,String> b : beds) { 
      out.write("\n");
      out.write("          <div class=\"unit-card ");
      out.print( b.get("status") );
      out.write("\">\n");
      out.write("            <div class=\"unit-number\">");
      out.print( b.get("number") );
      out.write("</div>\n");
      out.write("            <div class=\"unit-status\" style=\"color:");
      out.print( "available".equals(b.get("status"))?"var(--success)":"available".equals(b.get("status"))?"var(--danger)":"var(--warning)" );
      out.write("\">\n");
      out.write("              ");
      out.print( b.get("status") );
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print( b.get("type") );
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <div class=\"unit-actions\">\n");
      out.write("              <form action=\"manage_resources.jsp\" method=\"get\" style=\"display:inline\">\n");
      out.write("                <input type=\"hidden\" name=\"updateType\" value=\"bed\">\n");
      out.write("                <input type=\"hidden\" name=\"unitId\" value=\"");
      out.print( b.get("id") );
      out.write("\">\n");
      out.write("                <select name=\"status\" onchange=\"this.form.submit()\" style=\"width:100%\">\n");
      out.write("                  <option value=\"available\"   ");
      out.print( "available".equals(b.get("status"))?"selected":"" );
      out.write(">Available</option>\n");
      out.write("                  <option value=\"occupied\"    ");
      out.print( "occupied".equals(b.get("status"))?"selected":"" );
      out.write(">Occupied</option>\n");
      out.write("                  <option value=\"maintenance\" ");
      out.print( "maintenance".equals(b.get("status"))?"selected":"" );
      out.write(">Maintenance</option>\n");
      out.write("                </select>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- ICU -->\n");
      out.write("    <div class=\"card\">\n");
      out.write("      <div class=\"card-header\"><strong>🏥 ICU Units (");
      out.print( icus.size() );
      out.write(" total, ");
      out.print( availIcus );
      out.write(" available)</strong></div>\n");
      out.write("      <div class=\"card-body\">\n");
      out.write("        <div class=\"unit-grid\">\n");
      out.write("          ");
 for (Map<String,String> icu : icus) { 
      out.write("\n");
      out.write("          <div class=\"unit-card ");
      out.print( icu.get("status") );
      out.write("\">\n");
      out.write("            <div class=\"unit-number\">");
      out.print( icu.get("number") );
      out.write("</div>\n");
      out.write("            <div class=\"unit-status\">\n");
      out.write("              <span class=\"badge ");
      out.print( "available".equals(icu.get("status"))?"badge-success":"badge-danger" );
      out.write("\">\n");
      out.write("                ");
      out.print( icu.get("status") );
      out.write("\n");
      out.write("              </span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"unit-actions\">\n");
      out.write("              <form action=\"manage_resources.jsp\" method=\"get\">\n");
      out.write("                <input type=\"hidden\" name=\"updateType\" value=\"icu\">\n");
      out.write("                <input type=\"hidden\" name=\"unitId\" value=\"");
      out.print( icu.get("id") );
      out.write("\">\n");
      out.write("                <select name=\"status\" onchange=\"this.form.submit()\" style=\"width:100%\">\n");
      out.write("                  <option value=\"available\"   ");
      out.print( "available".equals(icu.get("status"))?"selected":"" );
      out.write(">Available</option>\n");
      out.write("                  <option value=\"occupied\"    ");
      out.print( "occupied".equals(icu.get("status"))?"selected":"" );
      out.write(">Occupied</option>\n");
      out.write("                  <option value=\"maintenance\" ");
      out.print( "maintenance".equals(icu.get("status"))?"selected":"" );
      out.write(">Maintenance</option>\n");
      out.write("                </select>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  </main>\n");
      out.write("</div>\n");
      out.write("<script src=\"js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
