/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-04-14 09:11:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.amritcare.dao.*;
import com.amritcare.model.*;
import java.util.List;

public final class manage_005fhospitals_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.amritcare.model");
    _jspx_imports_packages.add("com.amritcare.dao");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    if (session.getAttribute("loggedUser")==null) { response.sendRedirect("login.jsp"); return; }
    User user = (User) session.getAttribute("loggedUser");
    if (!"city_admin".equals(user.getRole())) { response.sendRedirect("login.jsp"); return; }

    HospitalDAO hDao = new HospitalDAO();
    String msg = "", msgType = "success";

    // Handle add
    String action = request.getParameter("action");
    if ("add".equals(action)) {
        Hospital h = new Hospital();
        h.setName(request.getParameter("name"));
        h.setLocation(request.getParameter("location"));
        h.setContact(request.getParameter("contact"));
        h.setSpecialization(request.getParameter("specialization"));
        try { h.setTotalBeds(Integer.parseInt(request.getParameter("totalBeds"))); } catch(Exception e){}
        try { h.setTotalIcu(Integer.parseInt(request.getParameter("totalIcu"))); }   catch(Exception e){}
        try { h.setLatitude(Double.parseDouble(request.getParameter("latitude"))); } catch(Exception e){}
        try { h.setLongitude(Double.parseDouble(request.getParameter("longitude"))); } catch(Exception e){}
        if (hDao.addHospital(h)) msg = "Hospital added successfully!";
        else { msg = "Failed to add hospital."; msgType = "danger"; }
    } else if ("deactivate".equals(action)) {
        hDao.updateStatus(Integer.parseInt(request.getParameter("id")), "inactive");
        msg = "Hospital deactivated.";
    } else if ("activate".equals(action)) {
        hDao.updateStatus(Integer.parseInt(request.getParameter("id")), "active");
        msg = "Hospital activated.";
    }

    List<Hospital> hospitals = hDao.getAllHospitals();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Manage Hospitals — AmritCare</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<nav class=\"navbar\">\n");
      out.write("  <a href=\"index.jsp\" class=\"navbar-brand\"><span class=\"logo-icon\">🏥</span> AmritCare</a>\n");
      out.write("  <ul class=\"nav-links\">\n");
      out.write("    <li><a href=\"admin_dashboard.jsp\">Dashboard</a></li>\n");
      out.write("    <li><a href=\"manage_hospitals.jsp\" class=\"active\">Hospitals</a></li>\n");
      out.write("    <li><a href=\"reports.jsp\">Reports</a></li>\n");
      out.write("    <li><a href=\"LogoutServlet\">Logout</a></li>\n");
      out.write("  </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"dashboard-layout\">\n");
      out.write("  <aside class=\"sidebar\">\n");
      out.write("    <div class=\"sidebar-user\"><div class=\"avatar\">A</div><div class=\"user-name\">City Admin</div><div class=\"user-role\">Super Admin</div></div>\n");
      out.write("    <ul class=\"sidebar-nav\">\n");
      out.write("      <li><a href=\"admin_dashboard.jsp\"><span class=\"nav-icon\">📊</span> Dashboard</a></li>\n");
      out.write("      <li><a href=\"manage_hospitals.jsp\" class=\"active\"><span class=\"nav-icon\">🏥</span> Hospitals</a></li>\n");
      out.write("      <li><a href=\"reports.jsp\"><span class=\"nav-icon\">📈</span> Reports</a></li>\n");
      out.write("      <li><a href=\"LogoutServlet\"><span class=\"nav-icon\">🚪</span> Logout</a></li>\n");
      out.write("    </ul>\n");
      out.write("  </aside>\n");
      out.write("\n");
      out.write("  <main class=\"dashboard-content\">\n");
      out.write("    <h1 style=\"font-family:'Playfair Display',serif;margin-bottom:1.5rem\">🏥 Manage Hospitals</h1>\n");
      out.write("\n");
      out.write("    ");
 if (!msg.isEmpty()) { 
      out.write("<div class=\"alert alert-");
      out.print( msgType );
      out.write('"');
      out.write('>');
      out.print( msg );
      out.write("</div>");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Add Hospital Form -->\n");
      out.write("    <div class=\"card mb-3\" style=\"margin-bottom:1.5rem\">\n");
      out.write("      <div class=\"card-header\"><strong>➕ Add New Hospital</strong></div>\n");
      out.write("      <div class=\"card-body\">\n");
      out.write("        <form action=\"manage_hospitals.jsp\" method=\"post\">\n");
      out.write("          <input type=\"hidden\" name=\"action\" value=\"add\">\n");
      out.write("          <div class=\"grid-2\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label>Hospital Name *</label>\n");
      out.write("              <input type=\"text\" name=\"name\" class=\"form-control\" required placeholder=\"Full hospital name\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label>Location *</label>\n");
      out.write("              <input type=\"text\" name=\"location\" class=\"form-control\" required placeholder=\"Area, Bhopal\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label>Contact</label>\n");
      out.write("              <input type=\"text\" name=\"contact\" class=\"form-control\" placeholder=\"Phone number\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label>Specializations</label>\n");
      out.write("              <input type=\"text\" name=\"specialization\" class=\"form-control\" placeholder=\"Cardiology, General, etc.\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label>Total Beds</label>\n");
      out.write("              <input type=\"number\" name=\"totalBeds\" class=\"form-control\" min=\"0\" value=\"50\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label>Total ICU Units</label>\n");
      out.write("              <input type=\"number\" name=\"totalIcu\" class=\"form-control\" min=\"0\" value=\"10\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label>Latitude (GPS)</label>\n");
      out.write("              <input type=\"text\" name=\"latitude\" class=\"form-control\" placeholder=\"e.g. 23.2599\" value=\"23.2599\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label>Longitude (GPS)</label>\n");
      out.write("              <input type=\"text\" name=\"longitude\" class=\"form-control\" placeholder=\"e.g. 77.4126\" value=\"77.4126\">\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <button type=\"submit\" class=\"btn btn-primary\">Add Hospital</button>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Hospital List -->\n");
      out.write("    <div class=\"table-wrapper\">\n");
      out.write("      <div class=\"card-header\"><strong>All Hospitals (");
      out.print( hospitals.size() );
      out.write(")</strong></div>\n");
      out.write("      <table>\n");
      out.write("        <thead>\n");
      out.write("          <tr><th>Name</th><th>Location</th><th>Contact</th><th>Beds</th><th>ICU</th><th>Rating</th><th>Action</th></tr>\n");
      out.write("        </thead>\n");
      out.write("        <tbody>\n");
      out.write("          ");
 for (Hospital h : hospitals) { 
      out.write("\n");
      out.write("          <tr>\n");
      out.write("            <td><strong>");
      out.print( h.getName() );
      out.write("</strong></td>\n");
      out.write("            <td style=\"font-size:0.85rem\">");
      out.print( h.getLocation() );
      out.write("</td>\n");
      out.write("            <td style=\"font-size:0.85rem\">");
      out.print( h.getContact() );
      out.write("</td>\n");
      out.write("            <td><span style=\"color:var(--success);font-weight:700\">");
      out.print( h.getAvailableBeds() );
      out.write("</span>/");
      out.print( h.getTotalBeds() );
      out.write("</td>\n");
      out.write("            <td><span style=\"color:var(--primary);font-weight:700\">");
      out.print( h.getAvailableIcu() );
      out.write("</span>/");
      out.print( h.getTotalIcu() );
      out.write("</td>\n");
      out.write("            <td>⭐ ");
      out.print( h.getRating() );
      out.write("</td>\n");
      out.write("            <td>\n");
      out.write("              <a href=\"manage_hospitals.jsp?action=deactivate&id=");
      out.print( h.getId() );
      out.write("\"\n");
      out.write("                 class=\"btn btn-danger btn-sm\"\n");
      out.write("                 onclick=\"return confirm('Deactivate this hospital?')\">Deactivate</a>\n");
      out.write("            </td>\n");
      out.write("          </tr>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  </main>\n");
      out.write("</div>\n");
      out.write("<script src=\"js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
