/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-04-14 09:10:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.amritcare.dao.*;
import com.amritcare.model.*;
import java.util.List;

public final class manage_005fdoctors_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.amritcare.model");
    _jspx_imports_packages.add("com.amritcare.dao");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    if (session.getAttribute("loggedUser")==null) { response.sendRedirect("login.jsp"); return; }
    User user = (User) session.getAttribute("loggedUser");
    if (!"hospital_admin".equals(user.getRole())) { response.sendRedirect("login.jsp"); return; }

    int hospitalId = user.getHospitalId();
    DoctorDAO dDao = new DoctorDAO();

    // Handle form submissions
    String action = request.getParameter("action");
    String msg = "", msgType = "success";

    if ("add".equals(action)) {
        Doctor d = new Doctor();
        d.setHospitalId(hospitalId);
        d.setName(request.getParameter("name"));
        d.setSpecialization(request.getParameter("specialization"));
        d.setQualification(request.getParameter("qualification"));
        try { d.setExperience(Integer.parseInt(request.getParameter("experience"))); } catch(Exception e){}
        d.setSchedule(request.getParameter("schedule"));
        if (dDao.addDoctor(d)) msg = "Doctor added successfully!";
        else { msg = "Failed to add doctor."; msgType = "danger"; }
    } else if ("toggle".equals(action)) {
        int docId = Integer.parseInt(request.getParameter("id"));
        String avail = request.getParameter("avail");
        dDao.updateAvailability(docId, avail);
        msg = "Doctor availability updated!";
    } else if ("delete".equals(action)) {
        int docId = Integer.parseInt(request.getParameter("id"));
        if (dDao.deleteDoctor(docId)) msg = "Doctor removed.";
        else { msg = "Could not remove doctor."; msgType = "danger"; }
    }

    List<Doctor> doctors = dDao.getDoctorsByHospital(hospitalId);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Manage Doctors — AmritCare</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<nav class=\"navbar\">\n");
      out.write("  <a href=\"index.jsp\" class=\"navbar-brand\"><span class=\"logo-icon\">🏥</span> AmritCare</a>\n");
      out.write("  <ul class=\"nav-links\">\n");
      out.write("    <li><a href=\"hospital_dashboard.jsp\">Dashboard</a></li>\n");
      out.write("    <li><a href=\"manage_resources.jsp\">Resources</a></li>\n");
      out.write("    <li><a href=\"manage_doctors.jsp\" class=\"active\">Doctors</a></li>\n");
      out.write("    <li><a href=\"LogoutServlet\">Logout</a></li>\n");
      out.write("  </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"dashboard-layout\">\n");
      out.write("  <aside class=\"sidebar\">\n");
      out.write("    <div class=\"sidebar-user\">\n");
      out.write("      <div class=\"avatar\">H</div>\n");
      out.write("      <div class=\"user-name\">Hospital Admin</div>\n");
      out.write("      <div class=\"user-role\">Hospital Staff</div>\n");
      out.write("    </div>\n");
      out.write("    <ul class=\"sidebar-nav\">\n");
      out.write("      <li><a href=\"hospital_dashboard.jsp\"><span class=\"nav-icon\">📊</span> Dashboard</a></li>\n");
      out.write("      <li><a href=\"manage_resources.jsp\"><span class=\"nav-icon\">🛏</span> Resources</a></li>\n");
      out.write("      <li><a href=\"manage_doctors.jsp\" class=\"active\"><span class=\"nav-icon\">👨‍⚕️</span> Doctors</a></li>\n");
      out.write("      <li><a href=\"LogoutServlet\"><span class=\"nav-icon\">🚪</span> Logout</a></li>\n");
      out.write("    </ul>\n");
      out.write("  </aside>\n");
      out.write("\n");
      out.write("  <main class=\"dashboard-content\">\n");
      out.write("\n");
      out.write("    <h1 style=\"font-family:'Playfair Display',serif;margin-bottom:1.5rem\">👨‍⚕️ Manage Doctors</h1>\n");
      out.write("\n");
      out.write("    ");
 if (!msg.isEmpty()) { 
      out.write("\n");
      out.write("      <div class=\"alert alert-");
      out.print( msgType );
      out.write('"');
      out.write('>');
      out.print( msg );
      out.write("</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Add Doctor Form -->\n");
      out.write("    <div class=\"card mb-3\" style=\"margin-bottom:1.5rem\">\n");
      out.write("      <div class=\"card-header\"><strong>➕ Add New Doctor</strong></div>\n");
      out.write("      <div class=\"card-body\">\n");
      out.write("        <form action=\"manage_doctors.jsp\" method=\"post\">\n");
      out.write("          <input type=\"hidden\" name=\"action\" value=\"add\">\n");
      out.write("          <div class=\"grid-2\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label>Doctor Name *</label>\n");
      out.write("              <input type=\"text\" name=\"name\" class=\"form-control\" placeholder=\"Dr. Full Name\" required>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label>Specialization *</label>\n");
      out.write("              <input type=\"text\" name=\"specialization\" class=\"form-control\" placeholder=\"e.g. Cardiology\" required>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label>Qualification</label>\n");
      out.write("              <input type=\"text\" name=\"qualification\" class=\"form-control\" placeholder=\"e.g. MBBS, MD\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label>Experience (years)</label>\n");
      out.write("              <input type=\"number\" name=\"experience\" class=\"form-control\" placeholder=\"Years of experience\" min=\"0\">\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label>Schedule</label>\n");
      out.write("            <input type=\"text\" name=\"schedule\" class=\"form-control\" placeholder=\"e.g. Mon-Fri 9AM-5PM\">\n");
      out.write("          </div>\n");
      out.write("          <button type=\"submit\" class=\"btn btn-primary\">Add Doctor</button>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Doctors List -->\n");
      out.write("    <div class=\"table-wrapper\">\n");
      out.write("      <div class=\"card-header\"><strong>Registered Doctors (");
      out.print( doctors.size() );
      out.write(")</strong></div>\n");
      out.write("      <table>\n");
      out.write("        <thead>\n");
      out.write("          <tr><th>Name</th><th>Specialization</th><th>Qualification</th><th>Exp.</th><th>Schedule</th><th>Status</th><th>Actions</th></tr>\n");
      out.write("        </thead>\n");
      out.write("        <tbody>\n");
      out.write("          ");
 for (Doctor d : doctors) { 
      out.write("\n");
      out.write("          <tr>\n");
      out.write("            <td><strong>Dr. ");
      out.print( d.getName() );
      out.write("</strong></td>\n");
      out.write("            <td>");
      out.print( d.getSpecialization() );
      out.write("</td>\n");
      out.write("            <td style=\"font-size:0.82rem\">");
      out.print( d.getQualification() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( d.getExperience() );
      out.write("y</td>\n");
      out.write("            <td style=\"font-size:0.82rem;color:var(--muted)\">");
      out.print( d.getSchedule() );
      out.write("</td>\n");
      out.write("            <td>\n");
      out.write("              ");
 if ("available".equals(d.getAvailability())) { 
      out.write("\n");
      out.write("                <span class=\"badge badge-success\">AVAILABLE</span>\n");
      out.write("              ");
 } else { 
      out.write("\n");
      out.write("                <span class=\"badge badge-danger\">");
      out.print( d.getAvailability().toUpperCase() );
      out.write("</span>\n");
      out.write("              ");
 } 
      out.write("\n");
      out.write("            </td>\n");
      out.write("            <td>\n");
      out.write("              ");
 String toggleAvail = "available".equals(d.getAvailability()) ? "unavailable" : "available"; 
      out.write("\n");
      out.write("              <a href=\"manage_doctors.jsp?action=toggle&id=");
      out.print( d.getId() );
      out.write("&avail=");
      out.print( toggleAvail );
      out.write("\"\n");
      out.write("                 class=\"btn btn-sm btn-outline\">\n");
      out.write("                ");
      out.print( "available".equals(d.getAvailability()) ? "Mark Unavailable" : "Mark Available" );
      out.write("\n");
      out.write("              </a>\n");
      out.write("              <a href=\"manage_doctors.jsp?action=delete&id=");
      out.print( d.getId() );
      out.write("\"\n");
      out.write("                 class=\"btn btn-danger btn-sm\"\n");
      out.write("                 onclick=\"return confirm('Remove Dr. ");
      out.print( d.getName() );
      out.write("?')\">✗</a>\n");
      out.write("            </td>\n");
      out.write("          </tr>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("          ");
 if (doctors.isEmpty()) { 
      out.write("\n");
      out.write("          <tr><td colspan=\"7\" style=\"text-align:center;color:var(--muted);padding:2rem\">No doctors added yet.</td></tr>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  </main>\n");
      out.write("</div>\n");
      out.write("<script src=\"js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
