/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-04-14 09:11:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.amritcare.dao.*;
import com.amritcare.model.*;
import java.util.*;

public final class reports_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.amritcare.model");
    _jspx_imports_packages.add("com.amritcare.dao");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    if (session.getAttribute("loggedUser")==null) { response.sendRedirect("login.jsp"); return; }
    User user = (User) session.getAttribute("loggedUser");
    if (!"city_admin".equals(user.getRole())) { response.sendRedirect("login.jsp"); return; }

    BookingDAO  bDao = new BookingDAO();
    HospitalDAO hDao = new HospitalDAO();
    List<Booking>  allBookings = bDao.getAllBookings();
    List<Hospital> hospitals   = hDao.getAllHospitals();

    long pendingCount   = allBookings.stream().filter(b->"pending".equals(b.getStatus())).count();
    long confirmedCount = allBookings.stream().filter(b->"confirmed".equals(b.getStatus())).count();
    long cancelledCount = allBookings.stream().filter(b->"cancelled".equals(b.getStatus())).count();
    long completedCount = allBookings.stream().filter(b->"completed".equals(b.getStatus())).count();
    long bedBookings    = allBookings.stream().filter(b->"Bed".equals(b.getBookingType())).count();
    long icuBookings    = allBookings.stream().filter(b->"ICU".equals(b.getBookingType())).count();
    long docBookings    = allBookings.stream().filter(b->"Doctor".equals(b.getBookingType())).count();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Reports & Analytics — AmritCare</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.0/chart.umd.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<nav class=\"navbar\">\n");
      out.write("  <a href=\"index.jsp\" class=\"navbar-brand\"><span class=\"logo-icon\">🏥</span> AmritCare</a>\n");
      out.write("  <ul class=\"nav-links\">\n");
      out.write("    <li><a href=\"admin_dashboard.jsp\">Dashboard</a></li>\n");
      out.write("    <li><a href=\"manage_hospitals.jsp\">Hospitals</a></li>\n");
      out.write("    <li><a href=\"reports.jsp\" class=\"active\">Reports</a></li>\n");
      out.write("    <li><a href=\"LogoutServlet\">Logout</a></li>\n");
      out.write("  </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"dashboard-layout\">\n");
      out.write("  <aside class=\"sidebar\">\n");
      out.write("    <div class=\"sidebar-user\"><div class=\"avatar\">A</div><div class=\"user-name\">City Admin</div><div class=\"user-role\">Super Admin</div></div>\n");
      out.write("    <ul class=\"sidebar-nav\">\n");
      out.write("      <li><a href=\"admin_dashboard.jsp\"><span class=\"nav-icon\">📊</span> Dashboard</a></li>\n");
      out.write("      <li><a href=\"manage_hospitals.jsp\"><span class=\"nav-icon\">🏥</span> Hospitals</a></li>\n");
      out.write("      <li><a href=\"reports.jsp\" class=\"active\"><span class=\"nav-icon\">📈</span> Reports</a></li>\n");
      out.write("      <li><a href=\"LogoutServlet\"><span class=\"nav-icon\">🚪</span> Logout</a></li>\n");
      out.write("    </ul>\n");
      out.write("  </aside>\n");
      out.write("\n");
      out.write("  <main class=\"dashboard-content\">\n");
      out.write("\n");
      out.write("    <h1 style=\"font-family:'Playfair Display',serif;margin-bottom:1.5rem\">📈 Analytics & Reports</h1>\n");
      out.write("\n");
      out.write("    <!-- Stats -->\n");
      out.write("    <div class=\"grid-4\" style=\"margin-bottom:2rem\">\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon blue\">📅</div>\n");
      out.write("        <div><div class=\"stat-value\">");
      out.print( allBookings.size() );
      out.write("</div><div class=\"stat-label\">Total Bookings</div></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon green\">✅</div>\n");
      out.write("        <div><div class=\"stat-value\">");
      out.print( confirmedCount+completedCount );
      out.write("</div><div class=\"stat-label\">Confirmed/Completed</div></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon orange\">⏳</div>\n");
      out.write("        <div><div class=\"stat-value\">");
      out.print( pendingCount );
      out.write("</div><div class=\"stat-label\">Pending</div></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"stat-card\">\n");
      out.write("        <div class=\"stat-icon red\">❌</div>\n");
      out.write("        <div><div class=\"stat-value\">");
      out.print( cancelledCount );
      out.write("</div><div class=\"stat-label\">Cancelled</div></div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Charts Row -->\n");
      out.write("    <div class=\"grid-2\" style=\"margin-bottom:2rem\">\n");
      out.write("      <div class=\"card\">\n");
      out.write("        <div class=\"card-header\"><strong>Bookings by Status</strong></div>\n");
      out.write("        <div class=\"card-body\">\n");
      out.write("          <canvas id=\"statusChart\" height=\"200\"></canvas>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"card\">\n");
      out.write("        <div class=\"card-header\"><strong>Bookings by Type</strong></div>\n");
      out.write("        <div class=\"card-body\">\n");
      out.write("          <canvas id=\"typeChart\" height=\"200\"></canvas>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Hospital Resource Bar Chart -->\n");
      out.write("    <div class=\"card mb-3\" style=\"margin-bottom:1.5rem\">\n");
      out.write("      <div class=\"card-header\"><strong>Hospital Resource Availability</strong></div>\n");
      out.write("      <div class=\"card-body\">\n");
      out.write("        <canvas id=\"resourceChart\" height=\"120\"></canvas>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- All Bookings Table -->\n");
      out.write("    <div class=\"table-wrapper\">\n");
      out.write("      <div class=\"card-header\"><strong>All Bookings (");
      out.print( allBookings.size() );
      out.write(")</strong></div>\n");
      out.write("      <table>\n");
      out.write("        <thead>\n");
      out.write("          <tr><th>#</th><th>Patient</th><th>Hospital</th><th>Type</th><th>Date</th><th>Contact</th><th>Status</th></tr>\n");
      out.write("        </thead>\n");
      out.write("        <tbody>\n");
      out.write("          ");
 for (Booking b : allBookings) {
               String bc="badge-secondary";
               if ("confirmed".equals(b.getStatus())) bc="badge-success";
               else if ("pending".equals(b.getStatus())) bc="badge-warning";
               else if ("cancelled".equals(b.getStatus())) bc="badge-danger";
               else if ("completed".equals(b.getStatus())) bc="badge-info";
          
      out.write("\n");
      out.write("          <tr>\n");
      out.write("            <td>#");
      out.print( b.getBookingId() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( b.getPatientName() );
      out.write("<br><small style=\"color:var(--muted)\">");
      out.print( b.getPatientEmail() );
      out.write("</small></td>\n");
      out.write("            <td>");
      out.print( b.getHospitalName() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( b.getBookingType() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( b.getBookingDate() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( b.getContact() );
      out.write("</td>\n");
      out.write("            <td><span class=\"badge ");
      out.print( bc );
      out.write('"');
      out.write('>');
      out.print( b.getStatus().toUpperCase() );
      out.write("</span></td>\n");
      out.write("          </tr>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  </main>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"js/main.js\"></script>\n");
      out.write("<script>\n");
      out.write("  // Status Pie Chart\n");
      out.write("  new Chart(document.getElementById('statusChart'), {\n");
      out.write("    type: 'doughnut',\n");
      out.write("    data: {\n");
      out.write("      labels: ['Pending','Confirmed','Completed','Cancelled'],\n");
      out.write("      datasets: [{\n");
      out.write("        data: [");
      out.print( pendingCount );
      out.write(',');
      out.print( confirmedCount );
      out.write(',');
      out.print( completedCount );
      out.write(',');
      out.print( cancelledCount );
      out.write("],\n");
      out.write("        backgroundColor: ['#ffd166','#06d6a0','#00b4d8','#ef233c'],\n");
      out.write("        borderWidth: 2\n");
      out.write("      }]\n");
      out.write("    },\n");
      out.write("    options: { plugins: { legend: { position: 'bottom' } }, cutout: '65%' }\n");
      out.write("  });\n");
      out.write("\n");
      out.write("  // Type Bar Chart\n");
      out.write("  new Chart(document.getElementById('typeChart'), {\n");
      out.write("    type: 'bar',\n");
      out.write("    data: {\n");
      out.write("      labels: ['Bed Bookings','ICU Bookings','Doctor Appointments'],\n");
      out.write("      datasets: [{\n");
      out.write("        label: 'Count',\n");
      out.write("        data: [");
      out.print( bedBookings );
      out.write(',');
      out.print( icuBookings );
      out.write(',');
      out.print( docBookings );
      out.write("],\n");
      out.write("        backgroundColor: ['#0077b6','#ef233c','#06d6a0'],\n");
      out.write("        borderRadius: 8\n");
      out.write("      }]\n");
      out.write("    },\n");
      out.write("    options: { plugins: { legend: { display:false } }, scales: { y: { beginAtZero:true } } }\n");
      out.write("  });\n");
      out.write("\n");
      out.write("  // Hospital Resource Chart\n");
      out.write("  new Chart(document.getElementById('resourceChart'), {\n");
      out.write("    type: 'bar',\n");
      out.write("    data: {\n");
      out.write("      labels: [");
 for(Hospital h:hospitals) out.print("'"+h.getName().replace("'","")+"',"); 
      out.write("],\n");
      out.write("      datasets: [\n");
      out.write("        { label:'Available Beds', data:[");
 for(Hospital h:hospitals) out.print(h.getAvailableBeds()+","); 
      out.write("], backgroundColor:'rgba(6,214,160,0.7)', borderRadius:4 },\n");
      out.write("        { label:'Available ICU',  data:[");
 for(Hospital h:hospitals) out.print(h.getAvailableIcu()+","); 
      out.write("], backgroundColor:'rgba(0,119,182,0.7)', borderRadius:4 },\n");
      out.write("        { label:'Doctors Online', data:[");
 for(Hospital h:hospitals) out.print(h.getAvailableDoctors()+","); 
      out.write("], backgroundColor:'rgba(255,209,102,0.8)', borderRadius:4 }\n");
      out.write("      ]\n");
      out.write("    },\n");
      out.write("    options: { plugins: { legend: { position:'bottom' } }, scales: { x: { stacked:false }, y: { beginAtZero:true } } }\n");
      out.write("  });\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
